import * as crypto from "node:crypto";
import * as fs from "node:fs";
import * as os from "node:os";
import * as path from "node:path";

/**
 * Every QA launch gets one directory below this root. Nothing in this module
 * ever removes the root itself; cleanup is limited to a marker-verified child.
 */
export const QA_RUNTIME_DIRECTORY = "breadboard-qa-runtime";
export const QA_RUN_MARKER = ".breadboard-qa-run.json";

export type QaPreservePolicy = "never" | "on-failure" | "always";
export type QaRunOutcome = "passed" | "failed" | "interrupted";
export type QaServiceProfile = "critical";
export type QaDesktopConfigProfile = "isolated-disabled" | "production-required";

export interface QaRunPaths {
  readonly repoRoot: string;
  readonly runtimeRoot: string;
  readonly runRoot: string;
  readonly userDataDir: string;
  /** The desktop resolver's mutable root: `<userDataDir>/Data`. */
  readonly dataDir: string;
  readonly homeDir: string;
  readonly appDataDir: string;
  readonly localAppDataDir: string;
  readonly tempDir: string;
  readonly downloadsDir: string;
  readonly artifactsDir: string;
  readonly diagnosticsDir: string;
  readonly serviceLogsDir: string;
  /** Shared ChatMock writer/dashboard reader ledger inside disposable data. */
  readonly councilLedgerDir: string;
  /** Empty managed-policy root preventing Hermes machine-global fallback. */
  readonly hermesManagedDir: string;
  readonly hermesFilesDir: string;
  readonly comfyUiRuntimeDir: string;
  readonly comfyUiEnvDir: string;
  readonly optionalSourcesDir: string;
  readonly optionalStateDir: string;
  readonly markerFile: string;
}

export interface QaBootstrapValues {
  /** QA-only invite created in the isolated desktop config. */
  readonly initialInviteCode: string;
  /** In-memory credentials for a user that scenarios may register. */
  readonly auth: {
    readonly inviteCode: string;
    readonly username: string;
    readonly email: string;
    readonly password: string;
  };
}

export interface CreateQaEnvironmentOptions {
  /** Defaults to two directories above this file. */
  repoRoot?: string;
  /** Defaults to `<os temp>/breadboard-qa-runtime`. */
  runtimeRoot?: string;
  /** A filesystem-safe id. A timestamp/pid/random id is generated by default. */
  runId?: string;
  preserve?: QaPreservePolicy;
  /** Isolated critical local services. Broader profiles are intentionally rejected. */
  serviceProfile?: QaServiceProfile;
  /** Source of the small OS allowlist. Defaults to `process.env`. */
  baseEnv?: NodeJS.ProcessEnv;
  /** Additional inherited keys. Secret-looking names require explicit opt-in. */
  passthroughEnv?: readonly string[];
  /** Explicit launch-environment overrides. `undefined` removes a key. */
  env?: NodeJS.ProcessEnv;
  /**
   * Secret-looking override names that are known to contain disposable QA
   * values. Real user credentials must never be added here.
   */
  allowCredentialEnv?: readonly string[];
  /** Seed a QA-only desktop config; integrations stay disabled unless explicitly required. */
  seedDesktopConfig?: boolean;
  /** Defaults to disabled; completion burn-in may require the real GBrain service. */
  gbrainMode?: "disabled" | "required";
  /** Full desktop integration policy. Defaults to isolated-disabled. */
  desktopConfigProfile?: QaDesktopConfigProfile;
  /**
   * Optional read-only reference to the normal ChatMock provider session.
   * This is a path, never credential contents, and is not copied into QA.
   */
  providerAuthFile?: string;
}

export interface QaCleanupResult {
  readonly path: string;
  readonly removed: boolean;
  readonly preserved: boolean;
  readonly reason: string;
}

export interface QaRunEnvironment {
  readonly runId: string;
  readonly paths: QaRunPaths;
  readonly env: NodeJS.ProcessEnv;
  /** Append these to the Electron entrypoint arguments. */
  readonly launchArgs: readonly string[];
  /** Alias useful when composing `electron.launch({ args: [...] })`. */
  readonly electronArgs: readonly string[];
  readonly preserve: QaPreservePolicy;
  readonly bootstrap: QaBootstrapValues;
  cleanup(outcome?: QaRunOutcome): Promise<QaCleanupResult>;
}

interface QaRunMarkerContents {
  readonly schemaVersion: 1;
  readonly runId: string;
  readonly ownerPid: number;
  readonly repoRoot: string;
  readonly runtimeRoot: string;
  readonly runRoot: string;
  readonly createdAt: string;
}

interface QaDesktopIntegrationConfig {
  readonly gbrainMode: "disabled" | "required";
  readonly comfyUiMode: "disabled" | "managed";
  readonly uiTarsMode: "disabled" | "required";
  readonly cadMode: "disabled" | "optional";
  readonly colpaliMode: "disabled" | "optional";
  readonly humanizerMode: "disabled" | "local";
  readonly humanizerDevice: "auto";
  readonly cliproxyMode: "disabled" | "required";
  readonly scriberrEnabled: boolean;
}

const BASE_ENV_ALLOWLIST = [
  "SystemRoot",
  "SystemDrive",
  "windir",
  "ComSpec",
  "PATH",
  "Path",
  "PATHEXT",
  "NUMBER_OF_PROCESSORS",
  "PROCESSOR_ARCHITECTURE",
  "PROCESSOR_IDENTIFIER",
  "OS",
  "ProgramFiles",
  "ProgramFiles(x86)",
  "ProgramW6432",
  "LANG",
  "LC_ALL",
  "TERM",
  "CI",
] as const;

/**
 * Empty values take precedence over repository dotenv files, preventing a dev
 * dashboard launch from quietly loading the developer's real integrations.
 */
const DENIED_CREDENTIAL_ENV = [
  "OPENAI_API_KEY",
  "ANTHROPIC_API_KEY",
  "GOOGLE_API_KEY",
  "GEMINI_API_KEY",
  "GROQ_API_KEY",
  "MISTRAL_API_KEY",
  "XAI_API_KEY",
  "COHERE_API_KEY",
  "PERPLEXITY_API_KEY",
  "OPENROUTER_API_KEY",
  "COMPOSIO_API_KEY",
  "HF_TOKEN",
  "HUGGINGFACE_TOKEN",
  "ELEVENLABS_API_KEY",
  "FIRECRAWL_API_KEY",
  "TAVILY_API_KEY",
  "SERPER_API_KEY",
  "BRAVE_API_KEY",
  "GITHUB_TOKEN",
  "GH_TOKEN",
  "GITLAB_TOKEN",
  "NPM_TOKEN",
  "AWS_ACCESS_KEY_ID",
  "AWS_SECRET_ACCESS_KEY",
  "AWS_SESSION_TOKEN",
  "AZURE_OPENAI_API_KEY",
  "SUPABASE_SERVICE_ROLE_KEY",
  "STRIPE_SECRET_KEY",
  "POSTHOG_API_KEY",
  "SENTRY_AUTH_TOKEN",
] as const;

const RUN_ID_PATTERN = /^[A-Za-z0-9][A-Za-z0-9._-]{0,95}$/;

export function createQaRunId(now = new Date()): string {
  const timestamp = now.toISOString().replace(/[-:.TZ]/g, "").slice(0, 14);
  return `${timestamp}-${process.pid}-${crypto.randomUUID().slice(0, 8)}`;
}

export function isPathInside(parent: string, candidate: string): boolean {
  const parentPath = path.resolve(parent);
  const candidatePath = path.resolve(candidate);
  const relative = path.relative(parentPath, candidatePath);
  return relative === "" || (!relative.startsWith("..") && !path.isAbsolute(relative));
}

/** Resolve and return `candidate`, or throw if it escapes `parent`. */
export function assertPathInside(
  parent: string,
  candidate: string,
  label = "path",
): string {
  const resolved = path.resolve(candidate);
  if (!isPathInside(parent, resolved)) {
    throw new Error(`${label} must stay inside ${path.resolve(parent)}: ${resolved}`);
  }
  return resolved;
}

export function looksLikeCredentialEnvironmentKey(key: string): boolean {
  return /(?:^|_)(?:API_?KEY|AUTH|BEARER|COOKIE|CREDENTIAL|PASSWORD|PRIVATE_?KEY|SECRET|SESSION|TOKEN)(?:_|$)/i.test(
    key,
  );
}

export function shouldPreserveQaRun(
  policy: QaPreservePolicy,
  outcome: QaRunOutcome,
): boolean {
  if (policy === "always") return true;
  if (policy === "never") return false;
  // Interrupted teardown is evidence-bearing just like an assertion failure.
  return outcome !== "passed";
}

export function createQaEnvironment(
  options: CreateQaEnvironmentOptions = {},
): QaRunEnvironment {
  const repoRoot = path.resolve(options.repoRoot ?? findRepositoryRoot(process.cwd()));
  assertDirectory(repoRoot, "Breadboard repository root");
  const desktopIntegrations = resolveDesktopIntegrationConfig(options);

  const runtimeRoot = path.resolve(
    options.runtimeRoot ?? path.join(os.tmpdir(), QA_RUNTIME_DIRECTORY),
  );
  assertNotFilesystemRoot(runtimeRoot, "QA runtime root");
  if (samePath(runtimeRoot, repoRoot)) {
    throw new Error("QA runtime root cannot be the repository root");
  }
  prepareSafeRuntimeRoot(runtimeRoot);

  const runId = options.runId ?? createQaRunId();
  if (!RUN_ID_PATTERN.test(runId) || runId === "." || runId === "..") {
    throw new Error(
      `Invalid QA run id ${JSON.stringify(runId)}; use 1-96 letters, digits, dot, dash, or underscore`,
    );
  }

  const runRoot = assertPathInside(runtimeRoot, path.join(runtimeRoot, runId), "QA run root");
  if (samePath(runRoot, runtimeRoot)) {
    throw new Error("QA run root must be a child of the QA runtime root");
  }
  try {
    fs.mkdirSync(runRoot, { recursive: false });
  } catch (error) {
    if (isNodeError(error) && error.code === "EEXIST") {
      throw new Error(`QA run already exists: ${runRoot}`);
    }
    throw error;
  }

  const userDataDir = path.join(runRoot, "user-data");
  const dataDir = path.join(userDataDir, "Data");
  const homeDir = path.join(runRoot, "home");
  const appDataDir = path.join(homeDir, "AppData", "Roaming");
  const localAppDataDir = path.join(homeDir, "AppData", "Local");
  const tempDir = path.join(runRoot, "temp");
  const downloadsDir = path.join(runRoot, "downloads");
  const artifactsDir = path.join(runRoot, "artifacts");
  const diagnosticsDir = path.join(artifactsDir, "diagnostics");
  const serviceLogsDir = path.join(dataDir, "logs");
  const councilLedgerDir = path.join(dataDir, "chatmock", "council-runs");
  const hermesManagedDir = path.join(dataDir, "runtime", "hermes-managed");
  const hermesFilesDir = path.join(dataDir, "runtime", "hermes-files");
  const comfyUiRuntimeDir = path.join(dataDir, "runtime", "comfyui");
  const comfyUiEnvDir = path.join(dataDir, "runtime", "comfyui-venv");
  const optionalSourcesDir = path.join(dataDir, "runtime", "qa-optional-sources");
  const optionalStateDir = path.join(dataDir, "runtime", "qa-optional-state");
  const markerFile = path.join(runRoot, QA_RUN_MARKER);

  const paths: QaRunPaths = {
    repoRoot,
    runtimeRoot,
    runRoot,
    userDataDir,
    dataDir,
    homeDir,
    appDataDir,
    localAppDataDir,
    tempDir,
    downloadsDir,
    artifactsDir,
    diagnosticsDir,
    serviceLogsDir,
    councilLedgerDir,
    hermesManagedDir,
    hermesFilesDir,
    comfyUiRuntimeDir,
    comfyUiEnvDir,
    optionalSourcesDir,
    optionalStateDir,
    markerFile,
  };
  try {
    const providerAuthFile = validateProviderAuthFile(
      options.providerAuthFile,
      dataDir,
    );
    const normalizedOptions: CreateQaEnvironmentOptions = {
      ...options,
      ...(providerAuthFile ? { providerAuthFile } : {}),
    };
    for (const directory of [
      userDataDir,
      dataDir,
      homeDir,
      appDataDir,
      localAppDataDir,
      tempDir,
      downloadsDir,
      artifactsDir,
      diagnosticsDir,
      serviceLogsDir,
      councilLedgerDir,
      hermesManagedDir,
      hermesFilesDir,
      comfyUiRuntimeDir,
      comfyUiEnvDir,
      optionalSourcesDir,
      optionalStateDir,
    ]) {
      assertPathInside(runRoot, directory, "QA directory");
      fs.mkdirSync(directory, { recursive: true });
    }

    const marker: QaRunMarkerContents = {
      schemaVersion: 1,
      runId,
      ownerPid: process.pid,
      repoRoot,
      runtimeRoot,
      runRoot,
      createdAt: new Date().toISOString(),
    };
    fs.writeFileSync(markerFile, `${JSON.stringify(marker, null, 2)}\n`, {
      encoding: "utf8",
      flag: "wx",
      mode: 0o600,
    });

    const bootstrap = seedDesktopConfig(
      paths,
      options.seedDesktopConfig !== false,
      desktopIntegrations,
    );
    const env = controlledEnvironment(paths, normalizedOptions, desktopIntegrations);
    const launchArgs = [
      "--breadboard-dev",
      `--breadboard-user-data-dir=${userDataDir}`,
      "--breadboard-qa",
    ] as const;
    const preserve = options.preserve ?? "on-failure";

    const environment: QaRunEnvironment = {
      runId,
      paths,
      env,
      launchArgs,
      electronArgs: launchArgs,
      preserve,
      bootstrap,
      cleanup: (outcome = "interrupted") => cleanupQaEnvironment(environment, outcome),
    };
    return environment;
  } catch (error) {
    // This is a just-created, exact child with no opportunity for user data to
    // pre-exist. Best-effort rollback keeps half-created runs from accumulating.
    try {
      fs.rmSync(runRoot, { recursive: true, force: true });
    } catch {
      // Preserve the original setup error.
    }
    throw error;
  }
}

export async function cleanupQaEnvironment(
  run: Pick<QaRunEnvironment, "runId" | "paths" | "preserve">,
  outcome: QaRunOutcome = "interrupted",
): Promise<QaCleanupResult> {
  const { runtimeRoot, runRoot, markerFile } = run.paths;
  if (shouldPreserveQaRun(run.preserve, outcome)) {
    return {
      path: runRoot,
      removed: false,
      preserved: true,
      reason: run.preserve === "always" ? "preserve policy is always" : `run ${outcome}`,
    };
  }

  if (!fs.existsSync(runRoot)) {
    return {
      path: runRoot,
      removed: false,
      preserved: false,
      reason: "run directory was already absent",
    };
  }

  const marker = assertSafeCleanupTarget(runtimeRoot, runRoot, markerFile, run.runId);
  try {
    await fs.promises.rm(runRoot, {
      recursive: true,
      force: false,
      // Electron/Chromium and Windows Defender can release profile files a beat
      // after the process exit event. Keep the wait bounded while tolerating it.
      maxRetries: 8,
      retryDelay: 250,
    });
  } catch (error) {
    // Recursive removal can delete the marker before reaching a Chromium file
    // that is still locked. Restore it so a later, safe retry remains possible.
    restoreMarkerAfterPartialCleanup(runRoot, markerFile, marker);
    throw error;
  }
  return {
    path: runRoot,
    removed: true,
    preserved: false,
    reason: `run ${outcome}; preserve policy is ${run.preserve}`,
  };
}

function controlledEnvironment(
  paths: QaRunPaths,
  options: CreateQaEnvironmentOptions,
  desktopIntegrations: QaDesktopIntegrationConfig,
): NodeJS.ProcessEnv {
  const source = options.baseEnv ?? process.env;
  const result: NodeJS.ProcessEnv = {};
  const allowCredentialEnv = new Set(
    (options.allowCredentialEnv ?? []).map((key) => key.toUpperCase()),
  );

  const inherit = (key: string): void => {
    if (looksLikeCredentialEnvironmentKey(key) && !allowCredentialEnv.has(key.toUpperCase())) {
      throw new Error(
        `Refusing to inherit credential-like environment variable ${key}; use a disposable QA override and allowCredentialEnv explicitly`,
      );
    }
    const value = environmentValue(source, key);
    if (value !== undefined) result[canonicalEnvironmentKey(key)] = value;
  };

  for (const key of BASE_ENV_ALLOWLIST) {
    // PATH and Path are aliases on Windows. Only emit canonical PATH.
    if (key === "Path" && environmentValue(source, "PATH") !== undefined) continue;
    inherit(key);
  }
  for (const key of options.passthroughEnv ?? []) inherit(key);

  // Next's development server reads its own dotenv files after Electron has
  // launched it. Shadow keys (never values) so `.env.local` cannot rehydrate a
  // real integration credential that the controlled parent environment omitted.
  for (const key of repositoryDotenvKeys(paths.repoRoot)) {
    if (!BASE_ENV_ALLOWLIST.some((allowed) => allowed.toUpperCase() === key.toUpperCase())) {
      result[key] = "";
    }
  }

  const profileRoot = path.parse(paths.homeDir).root;
  const homeDrive = profileRoot.replace(/[\\/]$/, "");
  const relativeHome = path.relative(profileRoot, paths.homeDir);
  Object.assign(result, {
    HOME: paths.homeDir,
    USERPROFILE: paths.homeDir,
    APPDATA: paths.appDataDir,
    LOCALAPPDATA: paths.localAppDataDir,
    XDG_CONFIG_HOME: path.join(paths.homeDir, ".config"),
    XDG_CACHE_HOME: path.join(paths.homeDir, ".cache"),
    XDG_DATA_HOME: path.join(paths.homeDir, ".local", "share"),
    CODEX_HOME: path.join(paths.dataDir, "runtime", "codex"),
    HERMES_HOME: path.join(paths.dataDir, "runtime", "hermes"),
    CLAUDE_CONFIG_DIR: path.join(paths.homeDir, ".claude"),
    NPM_CONFIG_USERCONFIG: path.join(paths.homeDir, ".npmrc"),
    GIT_CONFIG_GLOBAL: path.join(paths.homeDir, ".gitconfig"),
    GIT_CONFIG_NOSYSTEM: "1",
    TEMP: paths.tempDir,
    TMP: paths.tempDir,
    TMPDIR: paths.tempDir,
    ...(process.platform === "win32"
      ? {
          HOMEDRIVE: homeDrive,
          HOMEPATH: `\\${relativeHome.replaceAll("/", "\\")}`,
        }
      : {}),
    CI: "1",
    USERNAME: "breadboard-qa",
    USER: "breadboard-qa",
    BREADBOARD_QA_MODE: "1",
    BREADBOARD_QA_RUN_ID: path.basename(paths.runRoot),
    BREADBOARD_QA_RUN_DIR: paths.runRoot,
    BREADBOARD_QA_ARTIFACTS_DIR: paths.artifactsDir,
    BREADBOARD_QA_SERVICE_PROFILE: options.serviceProfile ?? "critical",
    BREADBOARD_DATA_DIR: paths.dataDir,
    BREADBOARD_REPO_ROOT: paths.repoRoot,
    // These mirror the seeded config for development-mode QA. Packaged QA
    // removes the overrides and proves that the persisted production profile
    // itself is the lifecycle source of truth.
    GBRAIN_MODE: desktopIntegrations.gbrainMode,
    UI_TARS_MODE: desktopIntegrations.uiTarsMode,
    CAD_MODE: desktopIntegrations.cadMode,
    COLPALI_MODE:
      desktopIntegrations.colpaliMode === "disabled" ? "disabled" : "auto",
    HUMANIZER_MODE: desktopIntegrations.humanizerMode,
    CLIPROXY_MODE: desktopIntegrations.cliproxyMode,
    VIDEO_TRANSCRIPTION_ENABLED: desktopIntegrations.scriberrEnabled ? "true" : "false",
  });

  if (options.providerAuthFile) {
    result.BREADBOARD_QA_PROVIDER_AUTH_FILE = options.providerAuthFile;
  }

  for (const key of DENIED_CREDENTIAL_ENV) result[key] = "";

  for (const [key, value] of Object.entries(options.env ?? {})) {
    if (
      value &&
      looksLikeCredentialEnvironmentKey(key) &&
      !allowCredentialEnv.has(key.toUpperCase())
    ) {
      throw new Error(
        `Refusing non-empty credential-like QA environment override ${key}; add only a disposable key to allowCredentialEnv`,
      );
    }
    if (value === undefined) delete result[key];
    else result[key] = value;
  }

  // Electron interprets this variable before app code and would bypass the
  // product's real desktop lifecycle.
  delete result["ELECTRON_RUN_AS_NODE"];
  return result;
}

function validateProviderAuthFile(
  providerAuthFile: string | undefined,
  dataRoot: string,
): string | undefined {
  if (!providerAuthFile?.trim()) return undefined;
  const resolved = path.resolve(providerAuthFile.trim());
  let realPath: string;
  try {
    const stat = fs.statSync(resolved);
    if (!stat.isFile()) throw new Error("not a regular file");
    realPath = fs.realpathSync(resolved);
  } catch (error) {
    throw new Error(
      `BREADBOARD_QA_PROVIDER_AUTH_FILE must name an existing regular file: ${resolved}`,
      { cause: error },
    );
  }
  if (isPathInside(dataRoot, realPath)) {
    throw new Error(
      `BREADBOARD_QA_PROVIDER_AUTH_FILE must remain outside disposable QA data: ${realPath}`,
    );
  }
  return realPath;
}

function seedDesktopConfig(
  paths: QaRunPaths,
  enabled: boolean,
  desktopIntegrations: QaDesktopIntegrationConfig,
): QaBootstrapValues {
  const initialInviteCode = `BREAD${crypto.randomBytes(5).toString("hex").toUpperCase()}`;
  const auth = {
    inviteCode: initialInviteCode,
    username: `qa-${path.basename(paths.runRoot).slice(-12).toLowerCase()}`,
    email: `qa-${crypto.randomBytes(6).toString("hex")}@example.invalid`,
    password: `Breadboard-QA-${crypto.randomBytes(12).toString("base64url")}!`,
  } as const;
  if (!enabled) return { initialInviteCode, auth };

  const configDir = path.join(paths.dataDir, "config");
  const configPath = path.join(configDir, "desktop-config.json");
  assertPathInside(paths.runRoot, configPath, "QA desktop config");
  fs.mkdirSync(configDir, { recursive: true });
  const secret = (bytes = 32): string => crypto.randomBytes(bytes).toString("base64url");
  const config = {
    version: 2,
    nextAuthSecret: secret(),
    hermesSessionToken: secret(),
    hermesToolSecret: secret(),
    hermesCapabilitySecret: secret(),
    initialInviteCode,
    gbrainMode: desktopIntegrations.gbrainMode,
    gbrainAdapterSecret: secret(24),
    comfyUiMode: desktopIntegrations.comfyUiMode,
    comfyUiExternalUrl: null,
    uiTarsMode: desktopIntegrations.uiTarsMode,
    uiTarsAdapterSecret: secret(24),
    cadMode: desktopIntegrations.cadMode,
    cadServiceSecret: secret(24),
    colpaliMode: desktopIntegrations.colpaliMode,
    colpaliServiceSecret: secret(24),
    humanizerMode: desktopIntegrations.humanizerMode,
    humanizerDevice: desktopIntegrations.humanizerDevice,
    humanizerServiceSecret: secret(24),
    cliproxyMode: desktopIntegrations.cliproxyMode,
    scriberrEnabled: desktopIntegrations.scriberrEnabled,
    scriberrBaseUrl: null,
    scriberrUsername: "breadboard-qa",
    scriberrPassword: secret(24),
    migratedFrom: null,
    // The QA directory starts empty by design. Mark migration complete so the
    // desktop never offers to copy a developer's real checkout state into it.
    migrationVersion: 1,
  };
  fs.writeFileSync(configPath, `${JSON.stringify(config, null, 2)}\n`, {
    encoding: "utf8",
    flag: "wx",
    mode: 0o600,
  });
  return { initialInviteCode, auth };
}

function resolveDesktopIntegrationConfig(
  options: CreateQaEnvironmentOptions,
): QaDesktopIntegrationConfig {
  const profile = options.desktopConfigProfile ?? "isolated-disabled";
  if (profile !== "isolated-disabled" && profile !== "production-required") {
    throw new Error(`Unsupported QA desktop config profile: ${String(profile)}`);
  }
  if (
    options.gbrainMode !== undefined &&
    options.gbrainMode !== "disabled" &&
    options.gbrainMode !== "required"
  ) {
    throw new Error(`Unsupported QA GBrain mode: ${String(options.gbrainMode)}`);
  }

  const resolved: QaDesktopIntegrationConfig =
    profile === "production-required"
      ? {
          gbrainMode: "required",
          comfyUiMode: "managed",
          uiTarsMode: "required",
          cadMode: "optional",
          colpaliMode: "optional",
          humanizerMode: "local",
          humanizerDevice: "auto",
          cliproxyMode: "required",
          scriberrEnabled: true,
        }
      : {
          gbrainMode: options.gbrainMode ?? "disabled",
          comfyUiMode: "disabled",
          uiTarsMode: "disabled",
          cadMode: "disabled",
          colpaliMode: "disabled",
          humanizerMode: "disabled",
          humanizerDevice: "auto",
          cliproxyMode: "disabled",
          scriberrEnabled: false,
        };

  if (profile === "production-required") {
    if (options.gbrainMode === "disabled") {
      throw new Error("production-required QA config cannot disable GBrain");
    }
    const requiredEnvironment = {
      GBRAIN_MODE: "required",
      UI_TARS_MODE: "required",
      CAD_MODE: "optional",
      COLPALI_MODE: "auto",
      HUMANIZER_MODE: "local",
      CLIPROXY_MODE: "required",
      VIDEO_TRANSCRIPTION_ENABLED: "true",
    } as const;
    for (const [key, expected] of Object.entries(requiredEnvironment)) {
      const override = environmentValue(options.env ?? {}, key);
      if (override !== undefined && override !== expected) {
        throw new Error(
          `production-required QA config cannot override ${key}=${expected} with ${override}`,
        );
      }
    }
  }
  return Object.freeze(resolved);
}

function repositoryDotenvKeys(repoRoot: string): Set<string> {
  const keys = new Set<string>();
  const candidates = [
    path.join(repoRoot, ".env"),
    path.join(repoRoot, ".env.local"),
    path.join(repoRoot, ".env.development"),
    path.join(repoRoot, ".env.development.local"),
    path.join(repoRoot, "dashboard", ".env"),
    path.join(repoRoot, "dashboard", ".env.local"),
    path.join(repoRoot, "dashboard", ".env.development"),
    path.join(repoRoot, "dashboard", ".env.development.local"),
  ];
  for (const file of candidates) {
    if (!fs.existsSync(file)) continue;
    // Do not parse, expand, return, or log values. Only the key before `=` is
    // retained long enough to place an empty value in the child environment.
    for (const line of fs.readFileSync(file, "utf8").split(/\r?\n/)) {
      const match = /^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)\s*=/.exec(line);
      const key = match?.[1];
      if (key) keys.add(key);
    }
  }
  return keys;
}

function assertSafeCleanupTarget(
  runtimeRoot: string,
  runRoot: string,
  markerFile: string,
  expectedRunId: string,
): QaRunMarkerContents {
  assertNotFilesystemRoot(runtimeRoot, "QA runtime root");
  assertNotFilesystemRoot(runRoot, "QA cleanup target");
  if (samePath(runtimeRoot, runRoot)) {
    throw new Error("Refusing to remove the QA runtime root itself");
  }
  assertPathInside(runtimeRoot, runRoot, "QA cleanup target");
  if (
    !samePath(markerFile, path.join(runRoot, QA_RUN_MARKER)) ||
    !isPathInside(runRoot, markerFile)
  ) {
    throw new Error(`Refusing cleanup with an unexpected QA marker path: ${markerFile}`);
  }

  const rootStat = fs.lstatSync(runRoot);
  if (!rootStat.isDirectory() || rootStat.isSymbolicLink()) {
    throw new Error(`Refusing to remove a non-directory or symlink QA target: ${runRoot}`);
  }
  const markerStat = fs.lstatSync(markerFile);
  if (!markerStat.isFile() || markerStat.isSymbolicLink()) {
    throw new Error(`Refusing cleanup without a regular QA marker: ${markerFile}`);
  }

  const realRuntimeRoot = fs.realpathSync(runtimeRoot);
  const realRunRoot = fs.realpathSync(runRoot);
  if (samePath(realRuntimeRoot, realRunRoot) || !isPathInside(realRuntimeRoot, realRunRoot)) {
    throw new Error(`Resolved QA cleanup target escaped its runtime root: ${realRunRoot}`);
  }

  let marker: QaRunMarkerContents;
  try {
    marker = JSON.parse(fs.readFileSync(markerFile, "utf8")) as QaRunMarkerContents;
  } catch (error) {
    throw new Error(`Refusing cleanup because the QA marker is invalid: ${message(error)}`);
  }
  if (
    marker.schemaVersion !== 1 ||
    marker.runId !== expectedRunId ||
    !samePath(marker.runtimeRoot, runtimeRoot) ||
    !samePath(marker.runRoot, runRoot)
  ) {
    throw new Error(`Refusing cleanup because the QA marker does not match ${runRoot}`);
  }
  if (marker.ownerPid !== process.pid && processIsAlive(marker.ownerPid)) {
    throw new Error(
      `Refusing to remove QA run ${marker.runId}; its owner process ${marker.ownerPid} is still alive`,
    );
  }
  return marker;
}

function restoreMarkerAfterPartialCleanup(
  runRoot: string,
  markerFile: string,
  marker: QaRunMarkerContents,
): void {
  try {
    if (!fs.existsSync(runRoot)) return;
    const stat = fs.lstatSync(runRoot);
    if (!stat.isDirectory() || stat.isSymbolicLink()) return;
    if (fs.existsSync(markerFile)) return;
    fs.writeFileSync(markerFile, `${JSON.stringify(marker, null, 2)}\n`, {
      encoding: "utf8",
      flag: "wx",
      mode: 0o600,
    });
  } catch {
    // Preserve the original cleanup error; the caller still receives it.
  }
}

function processIsAlive(pid: number): boolean {
  if (!Number.isSafeInteger(pid) || pid <= 0) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch (error) {
    return isNodeError(error) && error.code === "EPERM";
  }
}

function environmentValue(env: NodeJS.ProcessEnv, requestedKey: string): string | undefined {
  if (env[requestedKey] !== undefined) return env[requestedKey];
  if (process.platform !== "win32") return undefined;
  const requested = requestedKey.toUpperCase();
  const actual = Object.keys(env).find((key) => key.toUpperCase() === requested);
  return actual ? env[actual] : undefined;
}

function canonicalEnvironmentKey(key: string): string {
  return process.platform === "win32" && key.toUpperCase() === "PATH" ? "PATH" : key;
}

function samePath(left: string, right: string): boolean {
  const a = path.resolve(left);
  const b = path.resolve(right);
  return process.platform === "win32" ? a.toLowerCase() === b.toLowerCase() : a === b;
}

function assertNotFilesystemRoot(candidate: string, label: string): void {
  const resolved = path.resolve(candidate);
  if (samePath(resolved, path.parse(resolved).root)) {
    throw new Error(`${label} cannot be a filesystem root: ${resolved}`);
  }
}

function assertDirectory(candidate: string, label: string): void {
  if (!fs.existsSync(candidate) || !fs.statSync(candidate).isDirectory()) {
    throw new Error(`Expected ${label} at ${candidate}`);
  }
}

/**
 * Establish the runtime root without following an existing filesystem link.
 * The pre-create ancestor check prevents a missing root from being created
 * through a linked parent, and the post-create check runs before any run child
 * is made. Comparing real and configured paths also catches junctions or other
 * reparse-point escapes that are not reported consistently as symlinks.
 */
function prepareSafeRuntimeRoot(candidate: string): void {
  let existingAncestor = candidate;
  let stat = lstatIfPresent(existingAncestor);
  while (!stat) {
    const parent = path.dirname(existingAncestor);
    if (samePath(parent, existingAncestor)) {
      throw new Error(`Could not find an existing ancestor for QA runtime root: ${candidate}`);
    }
    existingAncestor = parent;
    stat = lstatIfPresent(existingAncestor);
  }

  assertDirectSafeDirectory(
    existingAncestor,
    samePath(existingAncestor, candidate) ? "QA runtime root" : "QA runtime root ancestor",
  );
  if (!samePath(existingAncestor, candidate)) {
    fs.mkdirSync(candidate, { recursive: true });
  }
  assertDirectSafeDirectory(candidate, "QA runtime root");
}

function assertDirectSafeDirectory(candidate: string, label: string): void {
  const stat = fs.lstatSync(candidate);
  if (stat.isSymbolicLink()) {
    throw new Error(`${label} cannot be a symlink or junction: ${candidate}`);
  }
  if (!stat.isDirectory()) {
    throw new Error(`${label} must be a directory: ${candidate}`);
  }

  const realCandidate = fs.realpathSync(candidate);
  if (!samePath(realCandidate, candidate)) {
    throw new Error(
      `${label} resolved outside its configured path: ${candidate} -> ${realCandidate}`,
    );
  }
}

function lstatIfPresent(candidate: string): fs.Stats | undefined {
  try {
    return fs.lstatSync(candidate);
  } catch (error) {
    if (isNodeError(error) && (error.code === "ENOENT" || error.code === "ENOTDIR")) {
      return undefined;
    }
    throw error;
  }
}

function findRepositoryRoot(start: string): string {
  let current = path.resolve(start);
  for (;;) {
    if (
      fs.existsSync(path.join(current, "package.json")) &&
      fs.existsSync(path.join(current, "desktop")) &&
      fs.existsSync(path.join(current, "dashboard"))
    ) {
      return current;
    }
    const parent = path.dirname(current);
    if (samePath(parent, current)) {
      throw new Error(`Could not find the Breadboard repository above ${start}`);
    }
    current = parent;
  }
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error;
}

function message(error: unknown): string {
  return error instanceof Error ? error.message : String(error);
}
