// The files a hardware blueprint can be exported as.
//
// Every file listed here is actually produced from the stored design — there is
// no format advertised that the code cannot generate. KiCad, Gerber and other
// fabrication outputs are deliberately absent.

import { bomToCsv } from "./bom.ts";
import { createZip } from "./zip.ts";
import type { HardwareDesign } from "./types.ts";

export interface ExportFile {
  path: string;
  content: string;
  mimeType: string;
  description: string;
}

export function assemblyMarkdown(design: HardwareDesign): string {
  const lines: string[] = [
    `# ${design.title} — assembly`,
    "",
    design.summary,
    "",
    `Status: **${design.status}**.`,
    "",
    "Automated validation is not a substitute for checking each part's datasheet,",
    "measuring with a multimeter, using a current-limited supply, or having a",
    "qualified engineer review anything that matters.",
    "",
  ];
  for (const step of design.assemblySteps) {
    lines.push(`## ${step.index}. ${step.title}`, "", step.instruction, "");
    if (step.warning) lines.push(`> **Warning** ${step.warning}`, "");
    if (step.verification) lines.push(`*Check:* ${step.verification}`, "");
  }
  if (design.validationResults.length) {
    lines.push("## Validation", "");
    for (const finding of design.validationResults) {
      lines.push(
        `- **${finding.severity.toUpperCase()}** ${finding.title} — ${finding.message}${
          finding.remediation ? ` _${finding.remediation}_` : ""
        }`,
      );
    }
    lines.push("");
  }
  return lines.join("\n");
}

function componentResearchMarkdown(design: HardwareDesign): string {
  return [
    `# ${design.title} — online component research`,
    "",
    "These records are the source-backed lookup snapshot used by this blueprint.",
    "A found product was wired automatically only when its record was marked **used**.",
    "",
    ...(design.componentResearch ?? []).flatMap((record) => [
      `## ${record.requestedAs}`,
      "",
      `Status: **${record.status}**.`,
      "",
      record.definition
        ? `Candidate: ${record.definition.name}${record.definition.manufacturer ? ` — ${record.definition.manufacturer}` : ""}${record.definition.manufacturerPartNumber ? ` ${record.definition.manufacturerPartNumber}` : ""}.`
        : "No component definition was accepted.",
      "",
      record.note,
      "",
      ...record.sources.map((source) => `- [${source.title}](${source.url}) — ${source.kind}`),
      "",
    ]),
  ].join("\n");
}

export function designExportFiles(design: HardwareDesign): ExportFile[] {
  const files: ExportFile[] = [
    {
      path: "hardware-design.json",
      content: `${JSON.stringify(design, null, 2)}\n`,
      mimeType: "application/json",
      description: "The complete design, enough to reopen this blueprint.",
    },
    {
      path: "bom.csv",
      content: bomToCsv(design.bom),
      mimeType: "text/csv",
      description: "Bill of materials, with estimated prices marked as estimates.",
    },
    {
      path: "assembly.md",
      content: assemblyMarkdown(design),
      mimeType: "text/markdown",
      description: "Numbered build instructions with the checks between them.",
    },
  ];

  if (design.circuitJson !== undefined) {
    files.push({
      path: "circuit.json",
      content: `${JSON.stringify(design.circuitJson, null, 2)}\n`,
      mimeType: "application/json",
      description: "Circuit JSON (source-level subset): components, ports, nets and traces.",
    });
  }

  if (design.componentResearch?.length) {
    files.push({
      path: "component-research.md",
      content: componentResearchMarkdown(design),
      mimeType: "text/markdown",
      description: "Online component candidates, acceptance status, and manufacturer sources.",
    });
  }

  for (const file of design.firmware?.files ?? []) {
    files.push({
      path: `firmware/${file.path}`,
      content: file.content,
      mimeType: file.language === "markdown" ? "text/markdown" : "text/plain",
      description: `Firmware source: ${file.path}`,
    });
  }

  return files;
}

function projectReadme(design: HardwareDesign): string {
  return [
    `# ${design.title}`,
    "",
    design.summary,
    "",
    "| File | What it is |",
    "| --- | --- |",
    ...designExportFiles(design).map((file) => `| \`${file.path}\` | ${file.description} |`),
    "",
    "Generated by Breadboard's Hardware Blueprint agent. Automated validation does",
    "not replace reading the datasheets, measuring with a multimeter, using a",
    "current-limited supply, or a qualified review where that matters.",
    "",
  ].join("\n");
}

/** The downloadable project archive. Deterministic for a given design. */
export function designProjectZip(design: HardwareDesign): Uint8Array {
  return createZip([
    { path: "README.md", content: projectReadme(design) },
    ...designExportFiles(design).map((file) => ({
      path: file.path,
      content: file.content,
    })),
  ]);
}

export function projectZipFilename(design: HardwareDesign): string {
  const slug =
    design.title
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, "-")
      .replace(/^-|-$/g, "")
      .slice(0, 60) || "hardware-blueprint";
  return `${slug}-project.zip`;
}
