// Firmware project generation.
//
// The pin header is written straight from the compiler's assignments, so the
// firmware can only ever use the pins the wiring diagram shows. Application
// logic may be model-generated, but it is checked against that header before it
// is accepted: a body referencing a constant that does not exist is discarded in
// favour of the deterministic fallback rather than shipped broken.

import { firmwareDriver, genericDriver, type DriverContext } from "./firmware-drivers.ts";
import type { CompiledCircuit, PeripheralPlacement } from "./compiler.ts";
import type { FirmwareLogic } from "./schemas.ts";
import type { ComponentDefinition, FirmwareProject, HardwareProjectRequest } from "./types.ts";

export interface FirmwareGenerationResult {
  project: FirmwareProject;
  /** Constants generated_pins.h defines, for the model contract and tests. */
  pinConstants: string[];
  /** Set when supplied application logic was rejected and the fallback used. */
  rejectedLogicReason?: string;
}

/** Boards whose Wire library takes its pins from the board definition. */
const AVR_BOARDS = ["arduino-uno", "arduino-nano", "arduino-mega"];

/** How a controller pin id is written in Arduino-framework source. */
export function firmwarePinLiteral(definitionId: string, pinId: string): string {
  if (definitionId === "esp32-devkit-v1") {
    return pinId.replace(/^GPIO/, "");
  }
  if (definitionId === "raspberry-pi-pico") {
    return pinId.replace(/^GP/, "");
  }
  if (AVR_BOARDS.includes(definitionId)) {
    // A0..A15 are named constants in the core; digital pins are plain numbers.
    if (/^A\d+$/.test(pinId)) return pinId;
    return pinId.replace(/^D/, "");
  }
  return pinId;
}

function driverVariable(prefix: string, reference: string): string {
  return `${prefix}${reference.replace(/[^A-Za-z0-9]/g, "")}`;
}

interface PlacementFirmware {
  placement: PeripheralPlacement;
  definition: ComponentDefinition;
  context: DriverContext;
  driver: NonNullable<ReturnType<typeof firmwareDriver>>;
}

function collectPlacements(circuit: CompiledCircuit): PlacementFirmware[] {
  const result: PlacementFirmware[] = [];
  for (const placement of circuit.peripherals) {
    const pinConstants: Record<string, string> = {};
    for (const signal of placement.signalPins) {
      if (signal.assignment.constantName) {
        pinConstants[signal.peripheralPinId] = signal.assignment.constantName;
      }
    }
    if (placement.interfaceKind === "i2c") {
      pinConstants.SDA = "PIN_I2C_SDA";
      pinConstants.SCL = "PIN_I2C_SCL";
    }
    // Every part reaches the firmware. Without a hand-written template one is
    // synthesised from the pins the compiler assigned.
    const driver =
      firmwareDriver(placement.definition.id) ??
      genericDriver({
        definitionId: placement.definition.id,
        signals: placement.signalPins.flatMap((signal) => {
          const pin = placement.definition.pins.find(
            (candidate) => candidate.id === signal.peripheralPinId,
          );
          if (!pin || !signal.assignment.constantName) return [];
          const kind =
            pin.electricalType === "analog-output" || pin.functions.includes("analog-out")
              ? "analog"
              : pin.electricalType === "digital-input"
                ? "out"
                : "in";
          return [{ pinId: pin.id, label: pin.label, kind } as const];
        }),
      });
    result.push({
      placement,
      definition: placement.definition,
      driver,
      context: {
        reference: placement.instance.reference,
        variable: driverVariable(driver.variablePrefix, placement.instance.reference),
        pinConstants,
        i2cAddress: placement.i2cAddress,
        logicVoltage: circuit.profile.logicVoltage,
      },
    });
  }
  return result;
}

function generatedPinsHeader(circuit: CompiledCircuit): {
  content: string;
  constants: string[];
} {
  const constants: string[] = ["SERIAL_BAUD"];
  const lines = [
    "// Generated by Breadboard — Hardware Blueprint.",
    "// Every value below comes from the compiled circuit. Editing this file by",
    "// hand makes the firmware disagree with the wiring diagram.",
    "#pragma once",
    "",
    `// Board: ${circuit.controllerDefinition.name}`,
    `#define SERIAL_BAUD ${circuit.profile.firmware.serialBaud}`,
    "",
  ];

  const emitted = new Set<string>();
  for (const assignment of circuit.assignments) {
    if (!assignment.constantName || emitted.has(assignment.constantName)) continue;
    emitted.add(assignment.constantName);
    constants.push(assignment.constantName);
    const literal = firmwarePinLiteral(
      circuit.controllerDefinition.id,
      assignment.controllerPinId,
    );
    lines.push(
      `#define ${assignment.constantName} ${literal}  // ${assignment.controllerPinLabel}${
        assignment.componentId
          ? ` -> ${
              circuit.components.find((instance) => instance.id === assignment.componentId)
                ?.reference ?? ""
            } ${assignment.peripheralPinId ?? ""}`.trimEnd()
          : ""
      }`,
    );
  }

  const addresses = circuit.peripherals.filter((placement) => placement.i2cAddress);
  if (addresses.length) {
    lines.push("");
    for (const placement of addresses) {
      const name = `I2C_ADDR_${placement.instance.reference}`;
      constants.push(name);
      lines.push(`#define ${name} ${placement.i2cAddress}  // ${placement.definition.name}`);
    }
  }

  lines.push("");
  return { content: `${lines.join("\n")}\n`, constants };
}

function platformioIni(circuit: CompiledCircuit, libraries: string[]): string {
  const lines = [
    "; Generated by Breadboard — Hardware Blueprint.",
    "[env:" + circuit.profile.firmware.platformioEnvironment + "]",
    `platform = ${circuit.profile.firmware.platformioPlatform}`,
    `board = ${circuit.profile.firmware.platformioBoard}`,
    `framework = ${circuit.profile.firmware.framework}`,
    `monitor_speed = ${circuit.profile.firmware.serialBaud}`,
    "build_flags = -Wall",
  ];
  if (libraries.length) {
    lines.push("lib_deps =");
    for (const library of libraries) lines.push(`    ${library}`);
  }
  return `${lines.join("\n")}\n`;
}

/** Every `PIN_*` / `I2C_ADDR_*` identifier a body refers to. */
export function referencedGeneratedConstants(source: string): string[] {
  return [...new Set(source.match(/\b(?:PIN_[A-Z0-9_]+|I2C_ADDR_[A-Z0-9_]+|SERIAL_BAUD)\b/g) ?? [])];
}

function indent(lines: string[], spaces: number): string {
  const pad = " ".repeat(spaces);
  return lines
    .flatMap((line) => line.split("\n"))
    .map((line) => (line.trim() ? `${pad}${line}` : ""))
    .join("\n");
}

function mainSource(input: {
  circuit: CompiledCircuit;
  placements: PlacementFirmware[];
  includes: string[];
  logic: FirmwareLogic | null;
}): string {
  const { circuit, placements, includes, logic } = input;
  const usesI2c = placements.some((entry) => entry.placement.interfaceKind === "i2c");
  const wireBegin = AVR_BOARDS.includes(circuit.controllerDefinition.id)
    ? "Wire.begin();  // this board's I2C pins are fixed by the core"
    : "Wire.begin(PIN_I2C_SDA, PIN_I2C_SCL);";

  const declarations = placements.flatMap((entry) => entry.driver.declarations(entry.context));
  const setupLines = placements.flatMap((entry) => [
    `// ${entry.context.reference} — ${entry.definition.name}`,
    ...entry.driver.setup(entry.context),
    "",
  ]);
  const loopLines = logic?.loopBody.trim()
    ? logic.loopBody.trim().split("\n")
    : [
        ...placements.flatMap((entry) => [
          `// ${entry.context.reference}`,
          ...entry.driver.fallbackLoop(entry.context),
        ]),
        "delay(2000);",
      ];

  return [
    "// Generated by Breadboard — Hardware Blueprint.",
    `// Project: ${circuit.controllerDefinition.name}`,
    "// Pin numbers come from include/generated_pins.h and must not be changed here.",
    "",
    '#include <Arduino.h>',
    '#include "generated_pins.h"',
    ...includes,
    "",
    declarations.length ? "// ---- devices ----" : "",
    ...declarations,
    declarations.length ? "" : "",
    logic?.helperDeclarations.trim() ? "// ---- application helpers ----" : "",
    ...(logic?.helperDeclarations.trim() ? logic.helperDeclarations.trim().split("\n") : []),
    logic?.helperDeclarations.trim() ? "" : "",
    "bool hardwareReady = false;",
    "",
    "void setup() {",
    "  Serial.begin(SERIAL_BAUD);",
    "  const unsigned long serialDeadline = millis() + 3000UL;",
    "  while (!Serial && millis() < serialDeadline) { delay(10); }",
    '  Serial.println();',
    `  Serial.println(F("Breadboard hardware blueprint — ${escapeForF(circuit.controllerDefinition.name)}"));`,
    "",
    "  bool ok = true;",
    usesI2c ? `  ${wireBegin}` : "",
    usesI2c ? "" : "",
    indent(setupLines, 2),
    ...(logic?.setupBody.trim()
      ? ["  // ---- application set-up ----", indent(logic.setupBody.trim().split("\n"), 2), ""]
      : []),
    "  hardwareReady = ok;",
    "  if (!hardwareReady) {",
    '    Serial.println(F("One or more parts did not initialise. Check the wiring above before trusting any reading."));',
    "  } else {",
    '    Serial.println(F("All parts initialised."));',
    "  }",
    "}",
    "",
    "void loop() {",
    "  if (!hardwareReady) {",
    '    Serial.println(F("Halted: hardware did not initialise."));',
    "    delay(5000);",
    "    return;",
    "  }",
    "",
    indent(loopLines, 2),
    "}",
    "",
  ]
    .filter((line) => line !== undefined)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");
}

function escapeForF(value: string): string {
  return value.replace(/["\\]/g, "");
}

function readmeSource(input: {
  circuit: CompiledCircuit;
  request: HardwareProjectRequest;
  placements: PlacementFirmware[];
  libraries: string[];
}): string {
  const { circuit, placements, libraries } = input;
  const rows = circuit.assignments
    .filter((assignment) => assignment.constantName)
    .map((assignment) => {
      const owner = circuit.components.find(
        (instance) => instance.id === assignment.componentId,
      );
      return `| \`${assignment.constantName}\` | ${assignment.controllerPinLabel} | ${
        owner ? `${owner.reference} ${assignment.peripheralPinId ?? ""}`.trim() : "shared bus"
      } |`;
    });

  return [
    `# ${input.request.title ?? "Hardware blueprint firmware"}`,
    "",
    `Generated by Breadboard for ${circuit.controllerDefinition.name}.`,
    "",
    "## Pin map",
    "",
    "| Constant | Board pin | Connected to |",
    "| --- | --- | --- |",
    ...rows,
    "",
    "These come from `include/generated_pins.h`. Change the wiring in Breadboard rather than editing them here.",
    "",
    "## Parts",
    "",
    ...placements.map(
      (entry) =>
        `- **${entry.context.reference}** ${entry.definition.name}${
          entry.context.i2cAddress ? ` at I²C ${entry.context.i2cAddress}` : ""
        }`,
    ),
    "",
    "## Build",
    "",
    "```sh",
    "pio run",
    "pio run --target upload",
    `pio device monitor -b ${circuit.profile.firmware.serialBaud}`,
    "```",
    "",
    libraries.length
      ? `PlatformIO installs ${libraries.join(", ")} on the first build.`
      : "This project needs no external libraries.",
    "",
  ].join("\n");
}

export function generateFirmware(input: {
  circuit: CompiledCircuit;
  request: HardwareProjectRequest;
  logic?: FirmwareLogic | null;
}): FirmwareGenerationResult {
  const { circuit, request } = input;
  const placements = collectPlacements(circuit);
  const header = generatedPinsHeader(circuit);

  const libraries = [
    ...new Set(placements.flatMap((entry) => entry.driver.libraries)),
  ].sort();
  const includes = [
    ...new Set(placements.flatMap((entry) => entry.driver.includes)),
  ];

  // Reject application logic that reaches for a constant the header does not
  // define; the deterministic fallback then keeps the project buildable.
  let logic = input.logic ?? null;
  let rejectedLogicReason: string | undefined;
  if (logic) {
    const body = [logic.setupBody, logic.loopBody, logic.helperDeclarations].join("\n");
    const unknown = referencedGeneratedConstants(body).filter(
      (name) => !header.constants.includes(name),
    );
    if (unknown.length) {
      rejectedLogicReason = `The generated application logic referenced ${unknown.join(
        ", ",
      )}, which the compiled circuit does not define. The deterministic fallback loop was used instead.`;
      logic = null;
    }
  }

  const files: FirmwareProject["files"] = [
    { path: "platformio.ini", language: "ini", content: platformioIni(circuit, libraries) },
    { path: "include/generated_pins.h", language: "cpp", content: header.content },
    {
      path: "src/main.cpp",
      language: "cpp",
      content: mainSource({ circuit, placements, includes, logic }),
    },
    {
      path: "README.md",
      language: "markdown",
      content: readmeSource({ circuit, request, placements, libraries }),
    },
  ];

  const expectedSerialOutput =
    logic?.expectedSerialOutput?.trim() ||
    [
      `Breadboard hardware blueprint — ${circuit.controllerDefinition.name}`,
      ...placements.map((entry) => `OK   ${entry.context.reference} ${entry.definition.name} ready`),
      "All parts initialised.",
    ].join("\n");

  return {
    project: {
      platform: request.firmware.platform,
      language: request.firmware.language,
      entryFile: "src/main.cpp",
      files,
      dependencies: libraries.map((name) => ({ name })),
      buildInstructions: [
        "Install PlatformIO Core, or the PlatformIO IDE extension for VS Code.",
        "Open this folder as a PlatformIO project.",
        "Run `pio run` to compile. The first build downloads the listed libraries.",
      ],
      uploadInstructions: [
        `Connect ${circuit.controllerInstance.reference} over USB.`,
        "Run `pio run --target upload`.",
        `Run \`pio device monitor -b ${circuit.profile.firmware.serialBaud}\` to watch the serial output.`,
        `Without PlatformIO, open src/main.cpp in the Arduino IDE, select "${circuit.profile.firmware.arduinoBoardName}", add the libraries listed in platformio.ini, and upload.`,
      ],
      expectedSerialOutput,
    },
    pinConstants: header.constants,
    ...(rejectedLogicReason ? { rejectedLogicReason } : {}),
  };
}

/**
 * The contract handed to the model when it writes application logic: the fixed
 * parts, the fixed constants, and what it may call. It is explicitly forbidden
 * from touching electrical assignments.
 */
export function firmwareLogicBrief(circuit: CompiledCircuit): string {
  const placements = collectPlacements(circuit);
  const constants = generatedPinsHeader(circuit).constants;
  return [
    `Board: ${circuit.controllerDefinition.name} (${circuit.profile.logicVoltage} V logic, Arduino framework).`,
    "",
    "Parts already declared and initialised for you:",
    ...placements.map(
      (entry) =>
        `- ${entry.context.reference} ${entry.definition.name}: ${entry.driver
          .api(entry.context)
          .join("; ")}`,
    ),
    "",
    `Constants defined in include/generated_pins.h: ${constants.join(", ")}.`,
    "",
    "Rules:",
    "- Use only the constants listed above. Never write a raw pin number.",
    "- Never call pinMode, Wire.begin, or any .begin() for the parts above; set-up is already generated.",
    "- Never change which pin a part uses; the wiring diagram and the assembly steps depend on it.",
    "- setupBody runs at the end of setup(); loopBody is the whole body of loop().",
    "- Keep loopBody non-blocking or end it with a single delay().",
  ].join("\n");
}
