// Zod schemas for every structure the language model is allowed to produce.
//
// Nothing generated by a model reaches the compiler without passing through
// here first. The compiler owns pins, nets and validation; the model only ever
// supplies intent (a HardwareProjectRequest), a design modification, or
// firmware application logic.

import { z } from "zod";
import { HARDWARE_DESIGN_SCHEMA_VERSION } from "./types.ts";
import type {
  HardwareDesign,
  HardwareProjectRequest,
} from "./types.ts";

const boundedText = (max: number) => z.string().trim().max(max);

export const requestedPeripheralSchema = z.object({
  type: boundedText(120).min(1),
  quantity: z.number().int().min(1).max(16).catch(1),
  constraints: z.record(z.string(), z.unknown()).optional(),
});

export const communicationInterfaceSchema = z.enum([
  "i2c",
  "spi",
  "uart",
  "can",
  "usb",
  "wifi",
  "bluetooth",
  "ethernet",
]);

export const hardwareProjectRequestSchema = z.object({
  title: boundedText(160).optional(),
  purpose: boundedText(2_000).min(1),
  controller: boundedText(120).optional(),

  inputs: z.array(requestedPeripheralSchema).max(24).default([]),
  outputs: z.array(requestedPeripheralSchema).max(24).default([]),

  communication: z.array(communicationInterfaceSchema).max(8).default([]),

  power: z
    .object({
      source: z.enum(["usb", "battery", "external-supply", "unknown"]).default("unknown"),
      voltage: z.number().min(0).max(48).optional(),
      maximumCurrentMa: z.number().min(0).max(20_000).optional(),
    })
    .default({ source: "unknown" }),

  prototypeType: z.enum(["breadboard", "perfboard", "pcb"]).default("breadboard"),

  firmware: z
    .object({
      platform: z.enum(["arduino", "platformio", "esp-idf", "pico-sdk"]).default("platformio"),
      language: z.enum(["cpp", "c", "micropython"]).default("cpp"),
    })
    .default({ platform: "platformio", language: "cpp" }),

  constraints: z
    .object({
      maximumCost: z.number().min(0).max(100_000).optional(),
      beginnerFriendly: z.boolean().default(true),
      preferredComponents: z.array(boundedText(120)).max(24).default([]),
      forbiddenComponents: z.array(boundedText(120)).max(24).default([]),
    })
    .default({
      beginnerFriendly: true,
      preferredComponents: [],
      forbiddenComponents: [],
    }),
});

export type ParsedHardwareProjectRequest = z.infer<typeof hardwareProjectRequestSchema>;

export const hardwareDesignModificationSchema = z.object({
  operations: z
    .array(
      z.discriminatedUnion("type", [
        z.object({
          type: z.literal("replace-component"),
          targetComponentId: boundedText(120).min(1),
          replacementDefinitionId: boundedText(120).min(1),
        }),
        z.object({
          type: z.literal("add-component"),
          componentDefinitionId: boundedText(120).min(1),
          quantity: z.number().int().min(1).max(16).catch(1),
          requestedPurpose: boundedText(400).optional(),
        }),
        z.object({
          type: z.literal("remove-component"),
          targetComponentId: boundedText(120).min(1),
        }),
        z.object({
          type: z.literal("change-power"),
          source: z.object({
            source: z.enum(["usb", "battery", "external-supply", "unknown"]),
            voltage: z.number().min(0).max(48).optional(),
            maximumCurrentMa: z.number().min(0).max(20_000).optional(),
          }),
        }),
        z.object({
          type: z.literal("change-constraint"),
          key: boundedText(80).min(1),
          value: z.unknown(),
        }),
      ]),
    )
    .max(24)
    .default([]),
  /** Behaviour the user asked for in words, carried into firmware generation. */
  behaviourNotes: boundedText(2_000).optional(),
});

export type HardwareDesignModification = z.infer<typeof hardwareDesignModificationSchema>;

/**
 * One chat turn: either a fresh project or a change to the blueprint already in
 * this conversation. The model decides which, because that is a question about
 * what the person meant — everything downstream of it is deterministic.
 */
export const hardwareTurnSchema = z.object({
  mode: z.enum(["new", "modify"]),
  request: hardwareProjectRequestSchema.optional(),
  modification: hardwareDesignModificationSchema.optional(),
  /** One sentence for the chat reply. */
  note: boundedText(400).default(""),
});

export type HardwareTurn = z.infer<typeof hardwareTurnSchema>;

/** The model writes only the body of `applicationLoop` / `applicationSetup`. */
export const firmwareLogicSchema = z.object({
  setupBody: boundedText(8_000).default(""),
  loopBody: boundedText(12_000).default(""),
  helperDeclarations: boundedText(8_000).default(""),
  expectedSerialOutput: boundedText(1_200).default(""),
});

export type FirmwareLogic = z.infer<typeof firmwareLogicSchema>;

export interface SchemaFailure {
  ok: false;
  error: string;
  issues: string[];
}

export type SchemaResult<T> = { ok: true; value: T } | SchemaFailure;

function describeIssues(error: z.ZodError): string[] {
  return error.issues
    .slice(0, 12)
    .map((issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`);
}

export function parseWithSchema<T>(
  schema: z.ZodType<T>,
  value: unknown,
  label: string,
): SchemaResult<T> {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true, value: result.data };
  return {
    ok: false,
    error: `${label} did not match its schema.`,
    issues: describeIssues(result.error),
  };
}

/**
 * Parse a JSON string the model produced. Models routinely wrap JSON in fences
 * or prose, so the first balanced object is extracted before parsing — but the
 * result still has to satisfy the schema.
 */
export function parseModelJson<T>(
  schema: z.ZodType<T>,
  raw: string,
  label: string,
): SchemaResult<T> {
  const candidate = extractJsonObject(raw);
  if (candidate === null) {
    return {
      ok: false,
      error: `${label} contained no JSON object.`,
      issues: [],
    };
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(candidate);
  } catch (error) {
    return {
      ok: false,
      error: `${label} was not valid JSON.`,
      issues: [error instanceof Error ? error.message : "parse error"],
    };
  }
  return parseWithSchema(schema, parsed, label);
}

/** First balanced `{...}` in the text, ignoring braces inside string literals. */
export function extractJsonObject(raw: string): string | null {
  const text = raw.replace(/^\s*```(?:json)?/i, "").replace(/```\s*$/i, "");
  const start = text.indexOf("{");
  if (start < 0) return null;
  let depth = 0;
  let inString = false;
  let escaped = false;
  for (let index = start; index < text.length; index += 1) {
    const character = text[index];
    if (inString) {
      if (escaped) escaped = false;
      else if (character === "\\") escaped = true;
      else if (character === '"') inString = false;
      continue;
    }
    if (character === '"') inString = true;
    else if (character === "{") depth += 1;
    else if (character === "}") {
      depth -= 1;
      if (depth === 0) return text.slice(start, index + 1);
    }
  }
  return null;
}

const componentInstanceSchema = z.object({
  id: z.string().min(1),
  definitionId: z.string().min(1),
  reference: z.string().min(1),
  name: z.string().min(1),
  value: z.string().optional(),
  quantity: z.number().int().min(1),
  properties: z.record(z.string(), z.union([z.string(), z.number(), z.boolean()])),
  position: z
    .object({ x: z.number(), y: z.number(), rotation: z.number().optional() })
    .optional(),
  automaticallyAdded: z.boolean().optional(),
  additionReason: z.string().optional(),
});

const electricalNetSchema = z.object({
  id: z.string().min(1),
  name: z.string().min(1),
  role: z.enum([
    "power",
    "ground",
    "digital",
    "analog",
    "i2c-sda",
    "i2c-scl",
    "spi-clock",
    "spi-data",
    "chip-select",
    "uart-tx",
    "uart-rx",
    "other",
  ]),
  nominalVoltage: z.number().optional(),
  connections: z.array(
    z.object({ componentId: z.string().min(1), pinId: z.string().min(1) }),
  ),
});

/**
 * Structural check for a stored design. Used when a design is read back from
 * artifact storage — a persisted blueprint must be reopenable without rerunning
 * the model, so its shape is verified rather than assumed.
 */
export const hardwareDesignSchema = z.object({
  schemaVersion: z.string().min(1),
  id: z.string().min(1),
  title: z.string().min(1),
  summary: z.string(),
  status: z.enum(["ready", "ready-with-warnings", "needs-changes", "concept-only"]),
  request: hardwareProjectRequestSchema,
  decisions: z.array(
    z.object({
      category: z.string(),
      selection: z.string(),
      rationale: z.string(),
    }),
  ),
  components: z.array(componentInstanceSchema),
  nets: z.array(electricalNetSchema),
  validationResults: z.array(
    z.object({
      id: z.string().min(1),
      rule: z.string().min(1),
      severity: z.enum(["error", "warning", "info"]),
      title: z.string(),
      message: z.string(),
      componentIds: z.array(z.string()),
      netIds: z.array(z.string()),
      remediation: z.string().optional(),
    }),
  ),
  bom: z.array(
    z.object({
      reference: z.string(),
      componentDefinitionId: z.string(),
      name: z.string(),
      valueOrModel: z.string().optional(),
      quantity: z.number().int().min(1),
      purpose: z.string(),
      manufacturer: z.string().optional(),
      manufacturerPartNumber: z.string().optional(),
      estimatedUnitPrice: z.number().optional(),
      estimatedTotalPrice: z.number().optional(),
      priceIsEstimate: z.boolean(),
      substitutes: z.array(z.string()),
    }),
  ),
  assemblySteps: z.array(
    z.object({
      id: z.string().min(1),
      index: z.number().int().min(1),
      title: z.string(),
      instruction: z.string(),
      componentIds: z.array(z.string()),
      netIds: z.array(z.string()),
      verification: z.string().optional(),
      warning: z.string().optional(),
    }),
  ),
  // Absent on designs stored before the compiler carried its figures forward;
  // the overview falls back to reading them out of the summary there.
  powerEstimate: z
    .object({
      totalTypicalMa: z.number(),
      totalMaximumMa: z.number(),
      perRailTypicalMa: z.record(z.string(), z.number()),
      unknownComponentIds: z.array(z.string()),
    })
    .optional(),
  firmware: z
    .object({
      platform: z.string(),
      language: z.string(),
      entryFile: z.string(),
      files: z.array(
        z.object({
          path: z.string().min(1),
          language: z.string(),
          content: z.string(),
        }),
      ),
      dependencies: z.array(
        z.object({ name: z.string(), version: z.string().optional() }),
      ),
      buildInstructions: z.array(z.string()),
      uploadInstructions: z.array(z.string()),
      expectedSerialOutput: z.string().optional(),
    })
    .optional(),
  circuitJson: z.unknown().optional(),
});

export function parseStoredDesign(value: unknown): SchemaResult<HardwareDesign> {
  const result = parseWithSchema(hardwareDesignSchema, value, "The stored hardware design");
  if (!result.ok) return result;
  if (result.value.schemaVersion !== HARDWARE_DESIGN_SCHEMA_VERSION) {
    return {
      ok: false,
      error: `Unsupported design schema version ${result.value.schemaVersion}.`,
      issues: [`expected ${HARDWARE_DESIGN_SCHEMA_VERSION}`],
    };
  }
  return { ok: true, value: result.value as HardwareDesign };
}

/** Fill a partially specified request with the project's conservative defaults. */
export function withRequestDefaults(
  request: ParsedHardwareProjectRequest,
): HardwareProjectRequest {
  return {
    ...request,
    inputs: request.inputs ?? [],
    outputs: request.outputs ?? [],
    communication: request.communication ?? [],
  } satisfies HardwareProjectRequest;
}
