// Zod schemas for every structure a language model is allowed to produce, and
// for every structure read back out of storage.
//
// Nothing generated by a model reaches the CAD kernel without passing through
// here first, and nothing read from an artifact is rendered before its shape is
// verified — a design stored by an older build must announce itself rather than
// render half a part.

import { z } from "zod";
import {
  CAD_ARTIFACT_SCHEMA_VERSION,
  CAD_DESIGN_SCHEMA_VERSION,
  type CADDesignSpec,
  type ParametricCADArtifact,
} from "./types.ts";

const boundedText = (max: number) => z.string().trim().max(max);
const identifier = z
  .string()
  .trim()
  .min(1)
  .max(80)
  .regex(/^[A-Za-z][A-Za-z0-9_]*$/, "must be a Python-safe identifier");

export const cadParameterSchema = z.object({
  id: identifier,
  label: boundedText(120).min(1),
  value: z.union([z.number().finite(), boundedText(200), z.boolean()]),
  unit: boundedText(16).optional(),
  minimum: z.number().finite().optional(),
  maximum: z.number().finite().optional(),
  editable: z.boolean().default(true),
  source: z.enum(["user", "default", "derived"]),
  description: boundedText(400).optional(),
});

export const cadComponentSchema = z.object({
  id: boundedText(80).min(1),
  name: boundedText(120).min(1),
  quantity: z.number().int().min(1).max(64).catch(1),
  material: boundedText(80).optional(),
  bodyRole: z.enum(["primary", "lid", "fastener", "reference", "other"]).default("primary"),
});

export const cadConstraintSchema = z.object({
  id: boundedText(80).min(1),
  type: z.enum([
    "dimension",
    "clearance",
    "wall-thickness",
    "alignment",
    "symmetry",
    "hole",
    "fit",
    "printability",
    "custom",
  ]),
  description: boundedText(600).min(1),
  expected: z.unknown().optional(),
  tolerance: z.number().finite().min(0).max(100).optional(),
  unit: boundedText(16).optional(),
});

export const cadAssumptionSchema = z.object({
  id: boundedText(80).min(1),
  description: boundedText(600).min(1),
  reason: boundedText(600).min(1),
  userEditable: z.boolean().default(true),
});

export const cadAssemblyHardwareSchema = z.object({
  id: boundedText(80).min(1),
  name: boundedText(160).min(1),
  quantity: z.number().int().min(1).max(999).catch(1),
  purpose: boundedText(400).optional(),
});

export const cadAssemblyStepSchema = z.object({
  order: z.number().int().min(1).max(200),
  summary: boundedText(400).min(1),
  parts: z.array(boundedText(80)).max(24).default([]),
  hardware: z.array(boundedText(80)).max(24).optional(),
  detail: boundedText(1_200).optional(),
});

export const cadAssemblySchema = z.object({
  overview: boundedText(1_200).default(""),
  hardware: z.array(cadAssemblyHardwareSchema).max(64).default([]),
  steps: z.array(cadAssemblyStepSchema).max(64).default([]),
  notes: z.array(boundedText(600)).max(24).optional(),
});

export const cadExportSettingsSchema = z.object({
  stlLinearTolerance: z.number().gt(0).max(5).default(0.05),
  stlAngularTolerance: z.number().gt(0).max(2).default(0.2),
  generateStep: z.boolean().default(true),
  generateStl: z.boolean().default(true),
  generateGlb: z.boolean().default(true),
  generate3mf: z.boolean().default(true),
});

const dimensions = z.object({
  x: z.number().finite().gt(0).max(10_000),
  y: z.number().finite().gt(0).max(10_000),
  z: z.number().finite().gt(0).max(10_000),
});

export const cadDesignSpecSchema = z.object({
  schemaVersion: z.literal(CAD_DESIGN_SCHEMA_VERSION),
  projectId: boundedText(80).min(1),
  name: boundedText(160).min(1),
  description: boundedText(4_000).default(""),
  units: z.enum(["mm", "inch"]).default("mm"),
  manufacturingProcess: z.enum(["fdm", "sla", "sls", "unknown"]).default("fdm"),
  parameters: z.array(cadParameterSchema).max(120).default([]),
  components: z.array(cadComponentSchema).max(64).default([]),
  constraints: z.array(cadConstraintSchema).max(120).default([]),
  assumptions: z.array(cadAssumptionSchema).max(64).default([]),
  // Optional so that a design stored before assembly was recorded still reads
  // back and renders, rather than announcing itself as an unreadable manifest.
  assembly: cadAssemblySchema.optional(),
  exportSettings: cadExportSettingsSchema,
  declaredBoundingBox: z
    .object({
      x: z.number().finite().gt(0).max(10_000).optional(),
      y: z.number().finite().gt(0).max(10_000).optional(),
      z: z.number().finite().gt(0).max(10_000).optional(),
      tolerance: z.number().finite().min(0).max(50).optional(),
    })
    .optional(),
  printerBed: dimensions.optional(),
});

/**
 * The shape the model fills in. `projectId` and `schemaVersion` are Breadboard's
 * to assign, so the model never supplies them and cannot claim a project that
 * is not its own.
 */
export const cadDesignSpecDraftSchema = cadDesignSpecSchema.omit({
  schemaVersion: true,
  projectId: true,
});

export type CADDesignSpecDraft = z.infer<typeof cadDesignSpecDraftSchema>;

export const cadValidationIssueSchema = z.object({
  code: boundedText(80).min(1),
  severity: z.enum(["info", "warning", "error"]),
  message: boundedText(2_000).min(1),
  feature: boundedText(160).nullish().transform((value) => value ?? undefined),
  expected: z.unknown().nullish().transform((value) => value ?? undefined),
  actual: z.unknown().nullish().transform((value) => value ?? undefined),
  repairHint: boundedText(1_000).nullish().transform((value) => value ?? undefined),
});

export const cadFileReferenceSchema = z.object({
  projectId: boundedText(80).min(1),
  revision: z.number().int().min(1),
  // Every format the store can write, including the two a SolidWorks build
  // produces — a native part read back through a schema that did not list them
  // would fail to reopen.
  format: z.enum([
    "step",
    "stl",
    "glb",
    "3mf",
    "sldprt",
    "source",
    "operations",
    "spec",
    "report",
  ]),
  filename: boundedText(160).min(1),
  mimeType: boundedText(120).min(1),
  byteSize: z.number().int().min(0),
  sha256: z.string().regex(/^[0-9a-f]{64}$/),
  linearTolerance: z.number().finite().optional(),
  angularTolerance: z.number().finite().optional(),
});

const measurementsSchema = z.object({
  boundingBox: z.object({
    x: z.number().finite(),
    y: z.number().finite(),
    z: z.number().finite(),
    unit: boundedText(16),
  }),
  volume: z.number().finite().optional(),
  surfaceArea: z.number().finite().optional(),
  solidCount: z.number().int().min(0),
  triangleCount: z.number().int().min(0).optional(),
  bodies: z
    .array(
      z.object({
        name: boundedText(120),
        volume: z.number().finite(),
        surfaceArea: z.number().finite(),
        boundingBox: z.object({
          x: z.number().finite(),
          y: z.number().finite(),
          z: z.number().finite(),
        }),
        valid: z.boolean(),
        watertight: z.boolean(),
      }),
    )
    .max(64)
    .default([]),
});

export const parametricCadArtifactSchema = z.object({
  schemaVersion: z.literal(CAD_ARTIFACT_SCHEMA_VERSION),
  artifactType: z.literal("parametric-cad"),
  projectId: boundedText(80).min(1),
  revision: z.number().int().min(1),
  title: boundedText(240).min(1),
  status: z.enum(["draft", "valid", "valid-with-warnings", "invalid"]),
  designSpec: cadDesignSpecSchema,
  source: z.string().min(1).max(400_000),
  entrypoint: identifier,
  parameters: z
    .record(z.string(), z.union([z.number().finite(), z.string(), z.boolean()]))
    .default({}),
  previewFile: cadFileReferenceSchema.nullable(),
  exports: z.array(cadFileReferenceSchema).max(24),
  measurements: measurementsSchema,
  validation: z.object({
    passed: z.boolean(),
    checkedAt: z.string().min(1),
    issues: z.array(cadValidationIssueSchema).max(400),
  }),
  assumptions: z.array(boundedText(600)).max(64).default([]),
  disclaimers: z.array(boundedText(1_200)).max(24).default([]),
  revisionHistory: z
    .array(
      z.object({
        revision: z.number().int().min(1),
        parentRevision: z.number().int().min(1).nullable(),
        status: z.enum(["draft", "valid", "valid-with-warnings", "invalid"]),
        instruction: boundedText(4_000),
        parameterDiff: z
          .array(
            z.object({
              id: boundedText(80),
              from: z.unknown(),
              to: z.unknown(),
            }),
          )
          .max(200)
          .default([]),
        createdAt: z.string().min(1),
        validationPassed: z.boolean(),
        errorCount: z.number().int().min(0),
        warningCount: z.number().int().min(0),
        boundingBox: z
          .object({
            x: z.number().finite(),
            y: z.number().finite(),
            z: z.number().finite(),
          })
          .optional(),
      }),
    )
    .max(200)
    .default([]),
  generationLog: z
    .array(
      z.object({
        at: z.string().min(1),
        stage: boundedText(80),
        detail: boundedText(2_000),
      }),
    )
    .max(200)
    .default([]),
  provenance: z.object({
    engine: boundedText(60),
    engineVersion: boundedText(60),
    kernel: boundedText(60),
    kernelVersion: boundedText(60),
    pythonVersion: boundedText(60),
    serviceVersion: boundedText(60),
    model: boundedText(120),
    geometryAuthor: z.enum(["model", "deterministic-template"]).optional(),
    generatedAt: z.string().min(1),
    parentRevision: z.number().int().min(1).optional(),
    buildDurationMs: z.number().int().min(0).optional(),
  }),
});

export type SchemaResult<T> =
  | { ok: true; value: T }
  | { ok: false; error: string; issues: string[] };

export function parseWithSchema<T>(
  schema: z.ZodType<T>,
  value: unknown,
  subject: string,
): SchemaResult<T> {
  const result = schema.safeParse(value);
  if (result.success) return { ok: true, value: result.data };
  return {
    ok: false,
    error: `${subject} did not validate.`,
    issues: result.error.issues.map(
      (issue) => `${issue.path.join(".") || "(root)"}: ${issue.message}`,
    ),
  };
}

/**
 * Structural check for a stored artifact manifest. Used when a design is read
 * back out of artifact storage: a persisted design must be reopenable without
 * rerunning the model, so its shape is verified rather than assumed.
 */
export function parseStoredCadArtifact(
  value: unknown,
): SchemaResult<ParametricCADArtifact> {
  const result = parseWithSchema(
    parametricCadArtifactSchema,
    value,
    "The stored parametric CAD design",
  );
  if (!result.ok) return result;
  return { ok: true, value: result.value as ParametricCADArtifact };
}

export function parseStoredDesignSpec(value: unknown): SchemaResult<CADDesignSpec> {
  const result = parseWithSchema(cadDesignSpecSchema, value, "The stored design specification");
  return result.ok ? { ok: true, value: result.value as CADDesignSpec } : result;
}
