// The working directory behind one editable video.
//
// Hard Rule 12 of the clone's SKILL.md: every session output goes in an `edit/`
// directory beside the sources, never inside the project checkout. That is
// honoured literally here — the clone directory stays pristine and each artifact
// gets its own tree:
//
//   video-use/<userId>/<artifactId>/
//     source/<key><ext>          the retained original, never re-encoded
//     edit/                      everything the renderer writes
//       transcripts/<key>.json   Scribe output, cached (Hard Rule 9)
//       takes_packed.md          the packed transcript the planner reads
//       edl.json                 the cut, regenerated every pass
//       clips_graded/            per-segment extracts
//       final.mp4                what becomes the next artifact version
//
// Keying by artifact id is what makes the studio cheap on the second prompt:
// the source is already here, the transcript is already here, and only the
// planning and the render have to happen again.
//
// The retained original is the reason an edit is non-destructive. Every pass
// replays the whole program against it, so ten revisions produce one generation
// of encoding rather than ten, and "revert" needs nothing but an older program.

import { externalRuntimePath as path } from "../external-runtime-path.ts";
import { externalRuntimeFilesystem as fs } from "../external-runtime-filesystem.ts";
import { dashboardDataDir } from "../runtime-paths.ts";

/** The source key inside the EDL. One source per session, so one name. */
export const SOURCE_KEY = "source";

export interface VideoEditSession {
  artifactId: string;
  root: string;
  sourcePath: string;
  editDir: string;
  transcriptsDir: string;
  transcriptPath: string;
  packedTranscriptPath: string;
  edlPath: string;
  outputPath: string;
}

function sessionsRoot(): string {
  return path.join(dashboardDataDir(), "video-use");
}

function sessionRoot(userId: number, artifactId: string): string {
  // The artifact id is generated by the store (`art_<uuid>`), never by a
  // browser, but it lands in a path — so it is checked rather than trusted.
  if (!/^art_[a-z0-9-]{6,64}$/i.test(artifactId)) {
    throw new Error("That artifact id is not valid.");
  }
  return path.join(sessionsRoot(), String(userId), artifactId);
}

/**
 * Describe a session's layout. Pure path arithmetic — nothing is created and
 * nothing has to exist yet, so callers can ask what a session *would* look like
 * before deciding to open one.
 */
export function describeSession(input: {
  userId: number;
  artifactId: string;
  sourceExtension: string;
}): VideoEditSession {
  const root = sessionRoot(input.userId, input.artifactId);
  const extension = /^\.[a-z0-9]{1,8}$/i.test(input.sourceExtension)
    ? input.sourceExtension.toLowerCase()
    : ".mp4";
  const editDir = path.join(root, "edit");
  const transcriptsDir = path.join(editDir, "transcripts");
  return {
    artifactId: input.artifactId,
    root,
    sourcePath: path.join(root, "source", `${SOURCE_KEY}${extension}`),
    editDir,
    transcriptsDir,
    transcriptPath: path.join(transcriptsDir, `${SOURCE_KEY}.json`),
    packedTranscriptPath: path.join(editDir, "takes_packed.md"),
    edlPath: path.join(editDir, "edl.json"),
    outputPath: path.join(editDir, "final.mp4"),
  };
}

/** An existing session for this artifact, whatever extension its source has. */
export function findSession(userId: number, artifactId: string): VideoEditSession | null {
  const root = sessionRoot(userId, artifactId);
  const sourceDir = path.join(root, "source");
  let entries: string[];
  try {
    entries = fs.readdirSync(sourceDir);
  } catch {
    return null;
  }
  const source = entries.find((entry) => entry.startsWith(`${SOURCE_KEY}.`));
  if (!source) return null;
  return describeSession({
    userId,
    artifactId,
    sourceExtension: path.extname(source),
  });
}

/**
 * Open the session for an artifact, copying `originalPath` in as the retained
 * original the first time. A session that already holds a source keeps it: the
 * original is the one file in here that must never be replaced, or every later
 * revision would be planned against an already-edited video.
 */
export function openSession(input: {
  userId: number;
  artifactId: string;
  originalPath: string;
}): VideoEditSession {
  const existing = findSession(input.userId, input.artifactId);
  if (existing && fs.existsSync(existing.sourcePath)) {
    ensureDirectories(existing);
    return existing;
  }

  const session = describeSession({
    userId: input.userId,
    artifactId: input.artifactId,
    sourceExtension: path.extname(input.originalPath),
  });
  ensureDirectories(session);
  fs.mkdirSync(path.dirname(session.sourcePath), { recursive: true });
  const temporary = `${session.sourcePath}.${process.pid}.${Date.now()}.tmp`;
  fs.copyFileSync(input.originalPath, temporary);
  fs.renameSync(temporary, session.sourcePath);
  return session;
}

function ensureDirectories(session: VideoEditSession): void {
  fs.mkdirSync(session.transcriptsDir, { recursive: true });
  fs.mkdirSync(session.editDir, { recursive: true });
}

/**
 * Clear everything a previous render left, keeping the source and the cached
 * transcript. Segment extracts are named by index, so a cut that goes from
 * eight segments to five would otherwise concat three stale ones on the end.
 */
export function clearRenderOutputs(session: VideoEditSession): void {
  for (const entry of ["clips_graded", "clips_preview", "clips_draft"]) {
    try {
      fs.rmSync(path.join(session.editDir, entry), { recursive: true, force: true });
    } catch {
      // A directory that is not there needs no clearing.
    }
  }
  for (const entry of ["base.mp4", "base_preview.mp4", "base_draft.mp4", "concat.txt", "final.mp4"]) {
    try {
      fs.rmSync(path.join(session.editDir, entry), { force: true });
    } catch {
      // Same.
    }
  }
}

/** Drop an artifact's whole session — used when the artifact itself is deleted. */
export function discardSession(userId: number, artifactId: string): void {
  try {
    fs.rmSync(sessionRoot(userId, artifactId), { recursive: true, force: true });
  } catch {
    // A session that cannot be removed is disk use, not a failure worth raising.
  }
}
