"use client";

// Classroom's one settings surface: whether OpenMAIC is installed and built,
// and the run defaults underneath it.
//
// There is one thing to prepare — a Breadboard-owned copy of the OpenMAIC
// clone, with its dependencies installed and the app built — and the button
// that does it lives here rather than anywhere a run could reach. A lesson run
// that installed its own runtime would be a network install and a multi-minute
// build started by a sentence in a chat. Setup runs in the background and this
// dialog polls its progress, because it takes minutes the first time.

import { useCallback, useEffect, useState } from "react";
import AgentRunDefaults from "@/app/components/agents/agent-run-defaults";
import { CLASSROOM_AGENT_ID } from "@/lib/classroom/identity.ts";

interface SetupStatus {
  ready: boolean;
  reason: string;
  clone: { found: boolean; path: string };
  runtime: { path: string; installed: boolean; built: boolean };
  service: { running: boolean; baseUrl: string; model: string };
  setup: {
    running: boolean;
    step: string;
    log: string;
    error: string;
    startedAt: string | null;
    finishedAt: string | null;
  };
}

const POLL_MS = 4_000;

function lastLine(log: string): string {
  const lines = log.split(/\r?\n/).map((line) => line.trim()).filter(Boolean);
  return lines[lines.length - 1] ?? "";
}

export default function ClassroomSettingsDialog({ onClose }: { onClose: () => void }) {
  const [status, setStatus] = useState<SetupStatus | null>(null);
  const [notice, setNotice] = useState("");
  const [busy, setBusy] = useState(false);

  const load = useCallback(async () => {
    try {
      const response = await fetch("/api/classroom/setup", { cache: "no-store" });
      const data = (await response.json()) as { status?: SetupStatus; error?: string };
      if (data.status) setStatus(data.status);
      else setNotice(data.error || "Setup could not be checked.");
    } catch {
      setNotice("Setup could not be checked.");
    }
  }, []);

  useEffect(() => {
    void load();
  }, [load]);

  // While setup runs, keep reading its progress.
  const running = Boolean(status?.setup.running);
  useEffect(() => {
    if (!running) return;
    const timer = setInterval(() => void load(), POLL_MS);
    return () => clearInterval(timer);
  }, [load, running]);

  async function install() {
    setBusy(true);
    setNotice("");
    try {
      const response = await fetch("/api/classroom/setup", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ action: "install" }),
      });
      const data = (await response.json()) as {
        status?: SetupStatus;
        message?: string;
        error?: string;
      };
      if (data.status) setStatus(data.status);
      setNotice(data.message || data.error || "Setup started.");
    } catch {
      setNotice("The install could not be started.");
    } finally {
      setBusy(false);
    }
  }

  async function stopServer() {
    setBusy(true);
    try {
      const response = await fetch("/api/classroom/setup", {
        method: "POST",
        headers: { "content-type": "application/json" },
        body: JSON.stringify({ action: "stop" }),
      });
      const data = (await response.json()) as { status?: SetupStatus; message?: string };
      if (data.status) setStatus(data.status);
      setNotice(data.message || "Stopped.");
    } catch {
      setNotice("The server could not be stopped.");
    } finally {
      setBusy(false);
    }
  }

  const setup = status?.setup;
  const progressLine = setup?.running
    ? `${setup.step}${lastLine(setup.log) ? ` — ${lastLine(setup.log)}` : ""}`
    : setup?.error
      ? `Setup failed: ${setup.error}`
      : "";

  return (
    <div
      className="bb-modal-backdrop fixed inset-0 z-[150] flex items-center justify-center p-4"
      onMouseDown={(event) => {
        if (event.target === event.currentTarget) onClose();
      }}
    >
      <section
        role="dialog"
        aria-modal="true"
        aria-labelledby="classroom-title"
        className="bb-modal-panel neu-dialog max-h-[85vh] w-full max-w-[42rem] overflow-y-auto rounded-2xl border text-[var(--ink)]"
      >
        <header className="flex items-start gap-3 border-b border-[var(--line)] p-5">
          <div className="min-w-0 flex-1">
            <h2 id="classroom-title" className="font-serif text-lg text-[var(--ink-heading)]">
              Classroom setup
            </h2>
            <p className="mt-1 text-xs leading-5 text-[var(--ink-muted)]">
              Turns a topic or the documents you attach into an interactive classroom — slides
              with an AI teacher, quizzes, simulations, and project work — generated by OpenMAIC
              on your configured model and played here.
            </p>
          </div>
          <button
            type="button"
            className="neu-button-icon h-9 w-9 rounded-full"
            onClick={onClose}
            aria-label="Close"
          >
            ×
          </button>
        </header>
        <div className="space-y-4 p-5">
          <div className="flex items-center gap-2">
            <span
              className={`h-2 w-2 rounded-full ${
                status?.ready ? "bg-[var(--botanical)]" : running ? "animate-pulse bg-amber-500" : "bg-amber-500"
              }`}
            />
            <span className="text-sm">
              {status?.ready
                ? status.service.running
                  ? `Ready · server running on ${status.service.model || "the chat's model"}`
                  : "Ready · server starts with the first lesson"
                : running
                  ? "Setting up"
                  : "Setup needed"}
            </span>
            <button
              type="button"
              className="neu-button ml-auto rounded-lg px-3 py-1.5 text-xs"
              onClick={() => void load()}
            >
              Refresh
            </button>
          </div>
          {notice || progressLine || status?.reason ? (
            <p className="text-xs leading-5 text-[var(--ink-muted)]" role="status">
              {progressLine || notice || status?.reason}
            </p>
          ) : null}
          <div className="bb-agent-run-panel space-y-1 p-3 text-xs leading-5 text-[var(--ink-muted)]">
            <p>
              <strong className="text-[var(--ink-heading)]">Clone:</strong>{" "}
              {status?.clone.found ? status.clone.path : "not found"}
            </p>
            <p>
              <strong className="text-[var(--ink-heading)]">Runtime:</strong>{" "}
              {status?.runtime.built
                ? "installed and built"
                : status?.runtime.installed
                  ? "installed, not built"
                  : "not installed"}
              {status?.runtime.path ? ` · ${status.runtime.path}` : ""}
            </p>
            <p>
              <strong className="text-[var(--ink-heading)]">Model layer:</strong> ChatMock, on the
              chat&apos;s model. Narration and images need a TTS or image provider OpenMAIC can
              reach; they are off by default.
            </p>
          </div>
          <div className="flex flex-wrap gap-2">
            <button
              type="button"
              disabled={busy || running || !status?.clone.found}
              className="neu-button rounded-lg px-3 py-2 text-xs disabled:opacity-50"
              onClick={() => void install()}
            >
              {status?.ready ? "Rebuild the runtime" : "Install and build OpenMAIC"}
            </button>
            {status?.service.running ? (
              <button
                type="button"
                disabled={busy}
                className="neu-button rounded-lg px-3 py-2 text-xs disabled:opacity-50"
                onClick={() => void stopServer()}
              >
                Stop the server
              </button>
            ) : null}
          </div>
          <AgentRunDefaults agentId={CLASSROOM_AGENT_ID} />
        </div>
      </section>
    </div>
  );
}
