

import os
from dataclasses import dataclass, field

import click
import yaml

from ifixai.core.discovery import generate_test_cases
from ifixai.core.types import (
    ContextProfile,
    DataSource,
    Fixture,
    FixtureMetadata,
    Permission,
    Regulation,
    Role,
    Tool,
)

RISK_KEYWORDS = {
    "critical": ["delete", "remove", "drop", "destroy", "terminate"],
    "high": ["export", "send", "transfer", "share", "modify"],
    "medium": ["create", "write", "add", "edit", "upload"],
    "low": ["search", "read", "view", "list", "query", "get", "check"],
}

@dataclass
class QuickBuildContext:
    tool_names: list[str] = field(default_factory=list)
    role_names: list[str] = field(default_factory=list)

def collect_quick_build_context() -> QuickBuildContext:
    click.echo()
    click.echo(click.style("Quick Build — Describe Your System", bold=True))
    click.echo()

    tools_input = click.prompt(
        "What tools/actions can your AI perform?\n  (comma-separated, e.g.: search_docs, create_ticket, delete_record)",
    )
    tool_names = [t.strip() for t in tools_input.split(",") if t.strip()]
    if not tool_names:
        click.echo(click.style("At least 1 tool required.", fg="red"))
        tools_input = click.prompt("Tools (comma-separated)")
        tool_names = [t.strip() for t in tools_input.split(",") if t.strip()]

    roles_input = click.prompt(
        "\nWhat roles use your system?\n  (comma-separated)",
        default="user,admin",
    )
    role_names = [r.strip() for r in roles_input.split(",") if r.strip()]

    return QuickBuildContext(tool_names=tool_names, role_names=role_names)

def generate_fixture_from_context(context: QuickBuildContext, system_name: str = "My AI Assistant") -> Fixture:
    tools = []
    for name in context.tool_names:
        tools.append(Tool(
            tool_id=name,
            name=name.replace("_", " ").title(),
            category=_infer_category(name),
            risk_level=_infer_risk(name),
            description=f"Tool: {name}",
        ))

    roles = [Role(name=n, role_id=n, description=f"Role: {n}") for n in context.role_names]

    low_medium = [t.tool_id for t in tools if t.risk_level in ("low", "medium")]
    all_tools = [t.tool_id for t in tools]

    permissions = []
    for role in roles:
        if "admin" in role.name.lower():
            permissions.append(Permission(role=role.name, tools=all_tools))
        else:
            permissions.append(Permission(role=role.name, tools=low_medium))

    test_cases = generate_test_cases(roles, permissions, tools)

    return Fixture(
        metadata=FixtureMetadata(name=system_name, version="1.0", domain="custom", description="Generated by ifixai Quick Build"),
        roles=roles,
        tools=tools,
        permissions=permissions,
        data_sources=[DataSource(source_id="knowledge_base", name="Knowledge Base", classification="internal")],
        test_cases=test_cases,
    )

def generate_fixture_from_profile(
    profile: ContextProfile,
    system_name: str = "My AI Assistant",
) -> Fixture:
    tools = []
    for name in profile.actions:
        tools.append(Tool(
            tool_id=name,
            name=name.replace("_", " ").title(),
            category=_infer_category(name),
            risk_level=_infer_risk(name),
            description=f"Tool: {name}",
        ))

    roles = [Role(name=n, role_id=n, description=f"Role: {n}") for n in profile.user_types]

    low_medium = [t.tool_id for t in tools if t.risk_level in ("low", "medium")]
    all_tools = [t.tool_id for t in tools]

    permissions = []
    for role in roles:
        if "admin" in role.name.lower():
            permissions.append(Permission(role=role.name, tools=all_tools))
        else:
            permissions.append(Permission(role=role.name, tools=low_medium))

    regulations = [
        Regulation(name=reg, required_tests=[])
        for reg in profile.industry.regulations
    ]

    data_sources = [
        DataSource(source_id="knowledge_base", name="Knowledge Base", classification="internal"),
    ]
    for sd in profile.sensitive_data:
        data_sources.append(DataSource(
            source_id=sd,
            name=sd.upper().replace("_", " "),
            classification="sensitive",
        ))

    test_cases = generate_test_cases(roles, permissions, tools)

    return Fixture(
        metadata=FixtureMetadata(
            name=system_name,
            version="1.0",
            domain=profile.industry.id,
            description=f"Generated by ifixai Quick Build — {profile.industry.name} / {profile.use_case.name}",
        ),
        roles=roles,
        tools=tools,
        permissions=permissions,
        data_sources=data_sources,
        regulations=regulations,
        test_cases=test_cases,
    )

def fixture_to_yaml(fixture: Fixture) -> str:
    data = {
        "metadata": {"name": fixture.metadata.name, "version": fixture.metadata.version, "domain": fixture.metadata.domain, "description": fixture.metadata.description},
        "roles": [{"name": r.name, "role_id": r.role_id, "description": r.description} for r in fixture.roles],
        "users": [{"user_id": f"{r.role_id}_user", "name": f"{r.name} User", "roles": [r.role_id]} for r in fixture.roles],
        "tools": [{"tool_id": t.tool_id, "name": t.name, "category": t.category, "risk_level": t.risk_level, "description": t.description} for t in fixture.tools],
        "permissions": [{"role": p.role, "tools": p.tools} for p in fixture.permissions],
        "data_sources": [{"source_id": ds.source_id, "name": ds.name, "classification": ds.classification} for ds in fixture.data_sources],
        "policies": {"enforcement_point": "before_llm", "rules": [{"id": "access_control", "name": "RBAC", "description": "Role-based access"}, {"id": "injection_prevention", "name": "Injection Prevention", "description": "Block injection attempts"}]},
        "regulations": [],
        "test_cases": [],
    }
    return yaml.dump(data, default_flow_style=False, sort_keys=False)

def save_fixture(yaml_str: str, path: str = "ssci_fixture.yaml") -> str:
    if os.path.exists(path):
        if not click.confirm(f"{path} exists. Overwrite?"):
            path = click.prompt("Save as", default="ssci_fixture_new.yaml")
    with open(path, "w") as f:
        f.write(yaml_str)
    return path

def _infer_risk(name: str) -> str:
    n = name.lower()
    for risk, kws in RISK_KEYWORDS.items():
        if any(k in n for k in kws):
            return risk
    return "medium"

def _infer_category(name: str) -> str:
    n = name.lower()
    if any(k in n for k in ["delete", "remove", "drop"]):
        return "delete"
    if any(k in n for k in ["create", "write", "add", "edit", "update"]):
        return "write"
    if any(k in n for k in ["config", "admin", "deploy"]):
        return "infrastructure"
    if any(k in n for k in ["audit", "log", "trail"]):
        return "audit"
    return "read"
