// Test-only deterministic adapter. Production cannot select this through a route or environment flag.
import AdmZip from 'adm-zip';
export function slicedFixture({ model = 'Bambu Lab P1S', nozzle = '0.4', materials = ['PLA','PLA'], colors = ['#112233','#445566'], positions = [0,1], plate = 1, estimates = true, extra = {}, unsliced = false, missing = false } = {}) {
  const zip = new AdmZip();
  if (!unsliced) {
    zip.addFile(`Metadata/plate_${plate}.gcode`, Buffer.from(`; generated by BambuStudio 2.3\n; printer_model = ${model}\n; nozzle_diameter = ${nozzle}\n; curr_bed_type = textured_plate\n; filament_type = ${materials.join(';')}\n; filament_colour = ${colors.join(';')}\n${estimates ? '; estimated printing time (normal mode) = 1h 20m\n; total filament weight [g] = 12.5\n' : ''}G1 X10 Y10 E1\nG1 X20 Y10 E2\n`));
    if (!missing) zip.addFile(`Metadata/plate_${plate}.json`, Buffer.from(JSON.stringify({ filament_ids: positions })));
  } else zip.addFile('3D/3dmodel.model', Buffer.from('<model/>'));
  for (const [name, data] of Object.entries(extra)) zip.addFile(name, Buffer.isBuffer(data) ? data : Buffer.from(data));
  return zip.toBuffer();
}
export function sources() {
  return [
    { id:'ams:0:0', unit:0, tray:0, label:'AMS 1 · Tray 1', material:'PLA', color:'#112233', available:true, provenance:'configured' },
    { id:'ams:1:0', unit:1, tray:0, label:'AMS 2 · Tray 1', material:'PLA', color:'#445566', available:true, provenance:'configured' },
  ];
}
export class FakePrinterAdapter {
  writes = [];
  reads = 0;
  uploadHold = null;
  startTimeout = false;
  busyAfterUpload = false;
  telemetry = { connected:true, state:'idle', sources:sources() };
  clock = Date.now();
  lastStart = null;
  async test(access) { return this.observe(access, true); }
  async observe() { this.reads++; this.clock=Math.max(Date.now(),this.clock+1); const at = new Date(this.clock).toISOString(); return { ...this.telemetry, observedAt:at, identityObservedAt:at, stateObservedAt:at }; }
  async upload(_access, input) { this.writes.push({ action:'upload', ...input }); if (this.uploadHold) await this.uploadHold; if (this.busyAfterUpload) this.telemetry.state='printing'; return { verified:'size' }; }
  async start(_access, input) { this.writes.push({action:'start',...input}); this.lastStart=input; if(this.startTimeout) throw new Error('Simulated lost acknowledgement after publish'); }
  async control(_access, input) { this.writes.push({action:'control',...input}); }
  report(state, fields = {}) { this.telemetry = { ...this.telemetry, state, filename:this.lastStart?.remoteFilename, taskId:this.lastStart?.attemptId, ...fields }; }
  async reap() {}
  async close() {}
}
