#!/usr/bin/env node
// Cross-platform launcher for the Hermes agent runtime (development stack).
//
// Hermes is Breadboard's conversational runtime behind the AgentRuntime
// abstraction. It binds to
// 127.0.0.1 only and authenticates every dashboard request with a bearer
// session token. The packaged desktop app supervises its own bundled Hermes;
// this launcher is the equivalent for `npm run dev` against the repo checkout.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadDashboardEnv, loadRootEnv } from "./load-root-env.mjs";
import { probeService } from "./service-probe.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
loadRootEnv(repoRoot);
loadDashboardEnv(repoRoot);

const hermesDir = path.join(repoRoot, "hermes-agent");
const port = process.env.HERMES_PORT || "9129";
const token = process.env.HERMES_DASHBOARD_SESSION_TOKEN?.trim();

if (!existsSync(hermesDir)) {
  console.error(`[hermes] Hermes checkout not found at ${hermesDir}`);
  process.exit(1);
}
if (!token) {
  console.error(
    "[hermes] HERMES_DASHBOARD_SESSION_TOKEN is not set. The dashboard and Hermes must share the same token;",
  );
  console.error("[hermes] set it in dashboard/.env.local (git-ignored) alongside HERMES_BASE_URL.");
  process.exit(1);
}

// The bundled desktop build ships its own CPython. In the repo the checkout's
// virtualenv is the equivalent; HERMES_PYTHON overrides both.
function resolvePython() {
  if (process.env.HERMES_PYTHON) return process.env.HERMES_PYTHON;
  const venv =
    process.platform === "win32"
      ? path.join(hermesDir, ".venv", "Scripts", "python.exe")
      : path.join(hermesDir, ".venv", "bin", "python");
  if (existsSync(venv)) return venv;
  return process.platform === "win32" ? "python.exe" : "python3";
}

// Deliberately NOT .runtime/hermes: that is the desktop shell's dev-mode
// HERMES_HOME (desktop/src/main/path-resolver.ts), and both this launcher and
// the desktop supervisor rewrite config.yaml and own live-session state. Running
// `npm run dev` and `npm run desktop:dev` at once must not corrupt either.
const hermesHome =
  process.env.HERMES_HOME || path.join(repoRoot, ".runtime", "hermes-stack");
mkdirSync(hermesHome, { recursive: true });

const chatmockBaseUrl = process.env.CHATMOCK_BASE_URL || "http://127.0.0.1:8765/v1";
const chatmockModel = process.env.CHATMOCK_MODEL || "default";

// Hermes reads its provider/toolset/memory profile from HERMES_HOME/config.yaml;
// the env vars alone leave it with "No LLM provider configured". This mirrors
// the desktop supervisor's generated config — Hermes state is disposable, so it
// is regenerated on every launch.
writeFileSync(
  path.join(hermesHome, "config.yaml"),
  [
    "# Generated by Breadboard. Hermes state is disposable and non-canonical.",
    "model:",
    `  default: ${JSON.stringify(chatmockModel)}`,
    "  provider: custom",
    `  base_url: ${JSON.stringify(chatmockBaseUrl)}`,
    // image_input_mode: native (below) governs the attach step, but a second
    // capability gate runs when the API request is built
    // (run_agent._prepare_messages_for_non_vision_model), and it treats
    // unknown vision capability as "no vision" — custom providers are never
    // in models.dev, so it stripped the just-attached pixels on every turn.
    // Declaring the capability satisfies that gate; it is honest because
    // every route ChatMock serves can carry images (Gemini/OpenAI-compat
    // pass-through, Claude via the CLI Read-file bridge).
    "  supports_vision: true",
    "toolsets:",
    "  - breadboard",
    "  - web",
    "web:",
    "  search_backend: ddgs",
    // Search without extract is the worst shape research can have: the model
    // gets titles and snippets it can never open, and answers from them as
    // though it had read the pages. Every extract backend Hermes ships —
    // Firecrawl, Tavily, Exa, Parallel — is a paid reader behind an API key,
    // so with none set `web_extract` failed on every call and the turn quietly
    // degraded to snippet-quoting. `fetch` is Breadboard's bundled provider
    // (plugins/web/fetch): it requests the page itself and strips it to text,
    // with the same SSRF and website-policy gates Firecrawl's loop applies.
    "  extract_backend: fetch",
    // Hermes ships a Mixture-of-Agents preset named "default" and, when no
    // provider is given, a plain model switch to a name matching an enabled
    // preset pivots the session onto the MoA virtual provider. Breadboard sends
    // exactly that string: every provider-prefixed model (`cliproxy/gemini-…`,
    // `anthropic/claude-…`) is addressed through ChatMock's `default` sentinel,
    // so picking one silently rerouted the turn to MoA's own reference models —
    // OpenRouter and Codex, neither of which has credentials here — and the
    // turn died with "HTTP 401: Missing Authentication header". Breadboard does
    // its own multi-model work inside ChatMock's council, so MoA is off.
    //
    // The per-preset flag is the one that matters: `load_config()` merges
    // Hermes's defaults, which already define `moa.presets.default`, and
    // `normalize_moa_config` reads the top-level `enabled` only when no
    // `presets` map exists. Setting just the top-level flag is a no-op here.
    "moa:",
    "  enabled: false",
    "  presets:",
    "    default:",
    "      enabled: false",
    "memory:",
    "  memory_enabled: false",
    "  user_profile_enabled: false",
    "display:",
    "  show_reasoning: true",
    "  busy_input_mode: steer",
    "  busy_steer_ack_enabled: false",
    "  memory_notifications: off",
    // Keep the full Breadboard tool catalog reachable without attaching all
    // of its schemas to every model request. This is required for Google
    // subscription models, whose gateway rejects the otherwise healthy turn
    // with RESOURCE_EXHAUSTED.
    "tools:",
    "  tool_search:",
    "    enabled: on",
    "agent:",
    "  coding_context: off",
    // An attached image must reach the model as pixels. Hermes' "auto" image
    // routing asks models.dev whether the active model has vision, and every
    // Breadboard model is addressed as provider `custom` — a name models.dev
    // has never heard of — so auto always resolved to "text": the image was
    // replaced by a `vision_analyze` summary, and when that side call failed
    // the model was told to call `vision_analyze` itself, which no Breadboard
    // session enables.
    "  image_input_mode: native",
    "",
  ].join("\n"),
  { encoding: "utf8" },
);
const env = {
  ...process.env,
  PYTHONUNBUFFERED: "1",
  PYTHONDONTWRITEBYTECODE: "1",
  HERMES_HOME: hermesHome,
  // Embedded profile: headless, no Hermes-owned memory, Breadboard-owned tools.
  HERMES_DESKTOP: "1",
  HERMES_SERVE_HEADLESS: "1",
  HERMES_DASHBOARD_SESSION_TOKEN: token,
  // Loopback callback target for the bundled `breadboard` plugin's tool calls.
  BREADBOARD_INTERNAL_URL: process.env.BREADBOARD_INTERNAL_URL || "http://127.0.0.1:3000",
  BREADBOARD_HERMES_TOOL_SECRET: process.env.BREADBOARD_HERMES_TOOL_SECRET || token,
  OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || chatmockBaseUrl,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "local",
  CHATMOCK_BASE_URL: chatmockBaseUrl,
  CHATMOCK_MODEL: process.env.CHATMOCK_MODEL || "default",
};

// Reuse an already-running instance instead of failing to bind the port
// (mirrors the Scriberr launcher).
//
// The probe deliberately avoids /api/status: that endpoint is Hermes's *public*
// liveness check and answers 200 to anyone, so it cannot tell our runtime from
// the desktop app's — which serves the same routes behind a different session
// token. Every other /api/ path is gated on that token before routing, so 401
// is exactly the "someone else's Hermes" signal, and the 404 for this
// deliberately non-existent path means the token was accepted.
const existing = await probeService({
  url: `http://127.0.0.1:${port}/api/__breadboard_adoption_probe`,
  headers: { Authorization: `Bearer ${token}` },
  acceptStatuses: [200, 204, 400, 404, 405],
});
if (existing === "running") {
  console.log(`[hermes] Already running and healthy on 127.0.0.1:${port} — reusing it.`);
  process.exit(0);
}
if (existing === "foreign") {
  console.error(`[hermes] Port ${port} is already in use by a server that rejected our session token.`);
  console.error(
    "[hermes] That is usually the installed desktop app's Hermes, which uses a different token and callback URL.",
  );
  console.error("[hermes] Stop it or set HERMES_PORT (and HERMES_BASE_URL) to a free port, then retry.");
  process.exit(1);
}

const child = spawn(
  resolvePython(),
  ["-m", "hermes_cli.main", "serve", "--isolated", "--host", "127.0.0.1", "--port", port, "--no-open"],
  { cwd: hermesDir, env, stdio: "inherit" },
);

child.on("error", (error) => {
  if (error.code === "ENOENT") {
    console.error("[hermes] Python was not found for the Hermes runtime.");
    console.error("[hermes] Create the checkout venv (`uv sync` in ./hermes-agent) or set HERMES_PYTHON.");
  } else {
    console.error(`[hermes] ${error.message}`);
  }
  process.exit(1);
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => child.kill(signal));
}
child.on("exit", (code) => process.exit(code ?? 0));
