#!/usr/bin/env node
// Cross-platform launcher for the Hermes agent runtime (development stack).
//
// Hermes is the runtime-neutral replacement for OpenHarness behind Breadboard's
// AgentRuntime abstraction (see docs/HERMES_RUNTIME_MIGRATION.md). It binds to
// 127.0.0.1 only and authenticates every dashboard request with a bearer
// session token. The packaged desktop app supervises its own bundled Hermes;
// this launcher is the equivalent for `npm run dev` against the repo checkout.

import { spawn } from "node:child_process";
import { existsSync, mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { loadDashboardEnv, loadRootEnv } from "./load-root-env.mjs";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
loadRootEnv(repoRoot);
loadDashboardEnv(repoRoot);

const hermesDir = path.join(repoRoot, "hermes-agent");
const port = process.env.HERMES_PORT || "9129";
const token = process.env.HERMES_DASHBOARD_SESSION_TOKEN?.trim();

if (!existsSync(hermesDir)) {
  console.error(`[hermes] Hermes checkout not found at ${hermesDir}`);
  process.exit(1);
}
if (!token) {
  console.error(
    "[hermes] HERMES_DASHBOARD_SESSION_TOKEN is not set. The dashboard and Hermes must share the same token;",
  );
  console.error("[hermes] set it in dashboard/.env.local (git-ignored) alongside HERMES_BASE_URL.");
  process.exit(1);
}

// The bundled desktop build ships its own CPython. In the repo the checkout's
// virtualenv is the equivalent; HERMES_PYTHON overrides both.
function resolvePython() {
  if (process.env.HERMES_PYTHON) return process.env.HERMES_PYTHON;
  const venv =
    process.platform === "win32"
      ? path.join(hermesDir, ".venv", "Scripts", "python.exe")
      : path.join(hermesDir, ".venv", "bin", "python");
  if (existsSync(venv)) return venv;
  return process.platform === "win32" ? "python.exe" : "python3";
}

// Deliberately NOT .runtime/hermes: that is the desktop shell's dev-mode
// HERMES_HOME (desktop/src/main/path-resolver.ts), and both this launcher and
// the desktop supervisor rewrite config.yaml and own live-session state. Running
// `npm run dev` and `npm run desktop:dev` at once must not corrupt either.
const hermesHome =
  process.env.HERMES_HOME || path.join(repoRoot, ".runtime", "hermes-stack");
mkdirSync(hermesHome, { recursive: true });

const chatmockBaseUrl = process.env.CHATMOCK_BASE_URL || "http://127.0.0.1:8765/v1";
const chatmockModel = process.env.CHATMOCK_MODEL || "gpt-5.6-sol";

// Hermes reads its provider/toolset/memory profile from HERMES_HOME/config.yaml;
// the env vars alone leave it with "No LLM provider configured". This mirrors
// the desktop supervisor's generated config — Hermes state is disposable, so it
// is regenerated on every launch.
writeFileSync(
  path.join(hermesHome, "config.yaml"),
  [
    "# Generated by Breadboard. Hermes state is disposable and non-canonical.",
    "model:",
    `  default: ${JSON.stringify(chatmockModel)}`,
    "  provider: custom",
    `  base_url: ${JSON.stringify(chatmockBaseUrl)}`,
    "toolsets:",
    "  - breadboard",
    "memory:",
    "  memory_enabled: false",
    "  user_profile_enabled: false",
    "display:",
    "  show_reasoning: true",
    "  busy_input_mode: steer",
    "  busy_steer_ack_enabled: false",
    "  memory_notifications: off",
    "agent:",
    "  coding_context: off",
    "",
  ].join("\n"),
  { encoding: "utf8" },
);
const env = {
  ...process.env,
  PYTHONUNBUFFERED: "1",
  PYTHONDONTWRITEBYTECODE: "1",
  HERMES_HOME: hermesHome,
  // Embedded profile: headless, no Hermes-owned memory, Breadboard-owned tools.
  HERMES_DESKTOP: "1",
  HERMES_SERVE_HEADLESS: "1",
  HERMES_DASHBOARD_SESSION_TOKEN: token,
  // Loopback callback target for the bundled `breadboard` plugin's tool calls.
  BREADBOARD_INTERNAL_URL: process.env.BREADBOARD_INTERNAL_URL || "http://127.0.0.1:3000",
  BREADBOARD_HERMES_TOOL_SECRET: process.env.BREADBOARD_HERMES_TOOL_SECRET || token,
  OPENAI_BASE_URL: process.env.OPENAI_BASE_URL || chatmockBaseUrl,
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "local",
  CHATMOCK_BASE_URL: chatmockBaseUrl,
  CHATMOCK_MODEL: process.env.CHATMOCK_MODEL || "gpt-5.6-sol",
};

// Reuse an already-running instance instead of failing to bind the port
// (mirrors the OpenHarness and Scriberr launchers).
async function probeExistingServer() {
  try {
    const response = await fetch(`http://127.0.0.1:${port}/api/status`, {
      headers: { Authorization: `Bearer ${token}` },
      signal: AbortSignal.timeout(2_500),
    });
    return response.status;
  } catch {
    return null; // Nothing answering HTTP — the port is presumably free.
  }
}

const existingStatus = await probeExistingServer();
if (existingStatus === 200) {
  console.log(`[hermes] Already running and healthy on 127.0.0.1:${port} — reusing it.`);
  process.exit(0);
}
if (existingStatus !== null) {
  console.error(
    `[hermes] Port ${port} is already in use (the existing server answered HTTP ${existingStatus}).`,
  );
  console.error(
    "[hermes] That is usually the installed desktop app's Hermes, which uses a different token and callback URL.",
  );
  console.error("[hermes] Stop it or set HERMES_PORT (and HERMES_BASE_URL) to a free port, then retry.");
  process.exit(1);
}

const child = spawn(
  resolvePython(),
  ["-m", "hermes_cli.main", "serve", "--isolated", "--host", "127.0.0.1", "--port", port, "--no-open"],
  { cwd: hermesDir, env, stdio: "inherit" },
);

child.on("error", (error) => {
  if (error.code === "ENOENT") {
    console.error("[hermes] Python was not found for the Hermes runtime.");
    console.error("[hermes] Create the checkout venv (`uv sync` in ./hermes-agent) or set HERMES_PYTHON.");
  } else {
    console.error(`[hermes] ${error.message}`);
  }
  process.exit(1);
});

for (const signal of ["SIGINT", "SIGTERM"]) {
  process.on(signal, () => child.kill(signal));
}
child.on("exit", (code) => process.exit(code ?? 0));
