import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";

test("authorized Garden tools search, read returned paths, and paginate without the graph pipeline", async (t) => {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), "garden-tool-roundtrip-"));
  process.env.BREADBOARD_DATA_DIR = root;
  process.env.QUARTZ_CONTENT_PATH = path.join(root, "content");
  process.env.BREADBOARD_EMBEDDINGS = "off";
  const { default: db } = await import("../src/lib/db.ts");
  const { executeGardenTool } = await import("../src/lib/hermes/garden-tools.ts");
  const { issueCapabilityToken } = await import("../src/lib/hermes/capability-token.ts");
  t.after(() => { db.close(); fs.rmSync(root, { recursive: true, force: true }); });
  const userId = Number(db.prepare("INSERT INTO users (username,email,password_hash) VALUES (?,?,?)").run("reader", "reader@example.test", "unused").lastInsertRowid);
  db.prepare("INSERT INTO clusters (user_id,name,slug) VALUES (?,?,?)").run(userId, "Course", "course");
  const garden = path.join(root, "content/course");
  fs.mkdirSync(path.join(garden, "sources"), { recursive: true });
  fs.mkdirSync(path.join(garden, "empty-destination"));
  fs.writeFileSync(path.join(garden, "sources/guide.md"), `---\ntitle: "Study guide"\nknowledge_type: "source-document"\nsource_type: "pdf"\nsource_file: "guide.pdf"\ntopics: ${JSON.stringify(Array(500).fill("ignored metadata"))}\n---\n# Assessment\nAttendance is compulsory for four MAC laboratory exercises.\n`);
  const rawToken = issueCapabilityToken({ userId, gardenId: "course", surface: "garden_chat", hermesSessionId: "read-test", allowedTools: ["garden_search", "garden_get_page", "garden_list_files"] });
  const search = await executeGardenTool({ rawToken, tool: "garden_search", args: { query: "compulsory MAC laboratory" } });
  assert.equal(search.ok, true, JSON.stringify(search));
  assert.equal(search.data.chunks[0].relPath, "sources/guide.md");
  const read = await executeGardenTool({ rawToken, tool: "garden_get_page", args: { slug: `course/${search.data.chunks[0].pageSlug}`, query: "attendance" } });
  assert.equal(read.ok, true);
  assert.match(read.data.content, /Attendance is compulsory/);
  assert.doesNotMatch(read.data.content, /ignored metadata/);
  assert.equal(read.data.nextOffset, null);
  const missing = await executeGardenTool({ rawToken, tool: "garden_get_page", args: { slug: "guide-old" } });
  assert.equal(missing.ok, false);
  assert.equal(missing.data.availableMatches[0].relPath, "sources/guide.md");
  const list = await executeGardenTool({ rawToken, tool: "garden_list_files", args: {} });
  assert.equal(list.ok, true);
  assert.ok(list.data.folders.some((folder) => folder.folder === "empty-destination" && folder.noteCount === 0));
  const denied = await executeGardenTool({ rawToken, tool: "garden_get_page", args: { gardenId: "private", slug: "guide" } });
  assert.equal(denied.ok, false);
});
