// Preparing the OpenMAIC runtime: a Breadboard-owned copy of the clone,
// installed and built.
//
// Setup runs only because a person pressed the button in the settings dialog,
// and it never touches the checkout. A staging copy of the source is made under
// the toolchains root, dependencies go in with pnpm through corepack, the app is
// built, and only then is the copy swapped into place — so a failed setup leaves
// the previous runtime exactly as it was.
//
// One change is made to the copy, and only on Windows. The `@openmaic/importer`
// package is bundled with `rollup-plugin-node-globals`, which inlines each
// module's `__dirname` as a path relative to `/`. On this machine that path
// begins `\Users\20252082\...`, and `\2` is an octal escape the parser refuses,
// so the build dies before it starts. Passing the package directory as the
// plugin's `baseDir` keeps the inlined paths relative and digit-free. It is
// applied to the copy, documented here and in docs/OPENMAIC_INTEGRATION.md, and
// worth sending upstream.

import { randomUUID } from "node:crypto";
import fs from "node:fs";
import path from "node:path";
import { spawn, type ChildProcess } from "node:child_process";
import { currentService, FRAME_ANCESTORS, stopService } from "./service.ts";
import {
  classroomAvailability,
  classroomDataDir,
  classroomDataLink,
  classroomRuntimeRoot,
  classroomStagingRoot,
  classroomToolsDir,
  corepackEntry,
  resolveClassroomSourceRoot,
} from "./runtime.ts";

export interface ClassroomSetupProgress {
  running: boolean;
  step: string;
  /** The last lines the install or build wrote, for a dialog to show. */
  log: string;
  error: string;
  startedAt: string | null;
  finishedAt: string | null;
}

export interface ClassroomSetupStatus {
  ready: boolean;
  reason: string;
  clone: { found: boolean; path: string };
  runtime: { path: string; installed: boolean; built: boolean };
  service: { running: boolean; baseUrl: string; model: string };
  setup: ClassroomSetupProgress;
}

interface SetupState extends ClassroomSetupProgress {
  child: ChildProcess | null;
  promise: Promise<void> | null;
}

const runtimeGlobal = globalThis as typeof globalThis & {
  __breadboardClassroomSetup?: SetupState;
};

const state: SetupState = runtimeGlobal.__breadboardClassroomSetup ?? {
  running: false,
  step: "",
  log: "",
  error: "",
  startedAt: null,
  finishedAt: null,
  child: null,
  promise: null,
};
runtimeGlobal.__breadboardClassroomSetup = state;

/** Directories that are build output, state, or not part of the app at all. */
const EXCLUDED_DIRECTORIES = new Set([
  ".git",
  ".github",
  ".next",
  ".worktrees",
  "node_modules",
  "data",
  "logs",
  "out",
  "coverage",
  "test-results",
  "playwright-report",
  "e2e",
  "eval",
]);

const INSTALL_TIMEOUT_MS = 30 * 60_000;
const BUILD_TIMEOUT_MS = 30 * 60_000;

export function setupStatus(env: NodeJS.ProcessEnv = process.env): ClassroomSetupStatus {
  const availability = classroomAvailability(env);
  const service = currentService();
  return {
    ready: availability.available,
    reason: availability.reason ?? "",
    clone: { found: availability.cloned, path: availability.sourceRoot ?? "" },
    runtime: {
      path: availability.runtimeRoot,
      installed: availability.installed,
      built: availability.built,
    },
    service: {
      running: Boolean(service),
      baseUrl: service?.baseUrl ?? "",
      model: service?.model ?? "",
    },
    setup: {
      running: state.running,
      step: state.step,
      log: state.log,
      error: state.error,
      startedAt: state.startedAt,
      finishedAt: state.finishedAt,
    },
  };
}

function copySource(source: string, staging: string): void {
  fs.mkdirSync(path.dirname(staging), { recursive: true });
  fs.cpSync(source, staging, {
    recursive: true,
    dereference: false,
    errorOnExist: false,
    filter: (from) => {
      const relative = path.relative(source, from);
      if (!relative) return true;
      const segments = relative.split(path.sep);
      if (segments.some((segment) => EXCLUDED_DIRECTORIES.has(segment))) return false;
      // The vendored parser bundle is regenerated by the install; a stale copy
      // would satisfy the build's assertion with the wrong bytes.
      if (relative.startsWith(path.join("public", "vendor", "maic-importer"))) return false;
      // Workspace package builds are regenerated too.
      if (/^packages[\\/].+[\\/]dist(?:[\\/]|$)/.test(relative)) return false;
      return true;
    },
  });
}

/** The Windows-only build fix described at the top of this file. */
export function applyImporterBuildFix(root: string, platform: NodeJS.Platform = process.platform): boolean {
  if (platform !== "win32") return false;
  const config = path.join(root, "packages", "@openmaic", "importer", "rollup.config.js");
  let source: string;
  try {
    source = fs.readFileSync(config, "utf8");
  } catch {
    return false;
  }
  if (source.includes("baseDir: process.cwd()")) return true;
  const patched = source.replace(/\bglobals\(\)/, "globals({ baseDir: process.cwd() })");
  if (patched === source) return false;
  fs.writeFileSync(config, patched, "utf8");
  return true;
}

/**
 * A `pnpm` on PATH for the install. OpenMAIC's postinstall runs `pnpm run build`
 * in every workspace package by bare name, and corepack is how pnpm is meant to
 * be reached here, so the shim just forwards to corepack through this Node.
 */
export function writePnpmShims(toolsDir: string, corepack: string, execPath: string = process.execPath): void {
  fs.mkdirSync(toolsDir, { recursive: true });
  fs.writeFileSync(
    path.join(toolsDir, "pnpm.cmd"),
    `@echo off\r\n"${execPath}" "${corepack}" pnpm %*\r\n`,
    "utf8",
  );
  fs.writeFileSync(
    path.join(toolsDir, "pnpm"),
    `#!/bin/sh\nexec "${execPath}" "${corepack}" pnpm "$@"\n`,
    { encoding: "utf8", mode: 0o755 },
  );
}

/**
 * The install and build environment. `ALLOWED_FRAME_ANCESTORS` is here and not
 * only at start because OpenMAIC's `next.config.ts` reads it while building —
 * the CSP header lands in the routes manifest — so a build without it serves
 * `frame-ancestors 'self'` whatever the server is later started with, and the
 * run card's frame stays blank. Found by framing one.
 */
export function installEnvironment(toolsDir: string, source: NodeJS.ProcessEnv = process.env): NodeJS.ProcessEnv {
  const pathKey = Object.keys(source).find((key) => key.toUpperCase() === "PATH") ?? "PATH";
  return {
    ...source,
    [pathKey]: `${toolsDir}${path.delimiter}${source[pathKey] ?? ""}`,
    COREPACK_ENABLE_DOWNLOAD_PROMPT: "0",
    COREPACK_ENABLE_STRICT: "0",
    NEXT_TELEMETRY_DISABLED: "1",
    NO_COLOR: "1",
    CI: "1",
    ALLOWED_FRAME_ANCESTORS: FRAME_ANCESTORS,
  };
}

function runStep(
  label: string,
  command: string,
  args: string[],
  options: { cwd: string; env: NodeJS.ProcessEnv; timeoutMs: number },
): Promise<void> {
  state.step = label;
  state.log = "";
  return new Promise((resolve, reject) => {
    const child = spawn(command, args, {
      cwd: options.cwd,
      env: options.env,
      windowsHide: true,
      stdio: ["ignore", "pipe", "pipe"],
    });
    state.child = child;
    const collect = (chunk: string) => {
      state.log = `${state.log}${chunk}`.slice(-6_000);
    };
    child.stdout?.setEncoding("utf8");
    child.stderr?.setEncoding("utf8");
    child.stdout?.on("data", collect);
    child.stderr?.on("data", collect);
    const timer = setTimeout(() => {
      try {
        child.kill();
      } catch {
        // Already gone.
      }
      reject(new Error(`${label} ran past its time limit and was stopped.`));
    }, options.timeoutMs);
    timer.unref?.();
    child.on("error", (error) => {
      clearTimeout(timer);
      reject(new Error(`${label} could not start: ${error.message}`));
    });
    child.on("exit", (code) => {
      clearTimeout(timer);
      state.child = null;
      if (code === 0) resolve();
      else reject(new Error(`${label} failed (exit ${code ?? "unknown"}).`));
    });
  });
}

/**
 * Point the runtime copy's `data` at the stable data directory. A junction on
 * Windows (no privilege needed), a symlink elsewhere; idempotent, and a real
 * directory already there — a classroom written before this existed — is
 * moved into the stable one rather than shadowed.
 */
export function ensureClassroomDataLink(
  link: string = classroomDataLink(),
  target: string = classroomDataDir(),
): void {
  fs.mkdirSync(target, { recursive: true });
  const existing = fs.lstatSync(link, { throwIfNoEntry: false });
  if (existing?.isSymbolicLink()) {
    try {
      if (path.resolve(fs.readlinkSync(link)) === path.resolve(target)) return;
    } catch {
      // Unreadable link: replaced below.
    }
    fs.rmSync(link, { recursive: false, force: true });
  } else if (existing?.isDirectory()) {
    for (const entry of fs.readdirSync(link)) {
      const from = path.join(link, entry);
      const to = path.join(target, entry);
      if (!fs.existsSync(to)) fs.renameSync(from, to);
    }
    fs.rmSync(link, { recursive: true, force: true });
  } else if (existing) {
    fs.rmSync(link, { force: true });
  }
  fs.mkdirSync(path.dirname(link), { recursive: true });
  fs.symlinkSync(target, link, process.platform === "win32" ? "junction" : "dir");
}

/**
 * The install and build happen at the runtime's final path, not in staging.
 * pnpm lays out `node_modules` with junctions whose targets are absolute, so a
 * tree installed under one directory and renamed to another points at a place
 * that no longer exists. The previous runtime is kept beside it until the new
 * one has built, and put back if it does not.
 */
async function perform(): Promise<void> {
  const source = resolveClassroomSourceRoot();
  if (!source) {
    throw new Error(
      "The OpenMAIC clone was not found. Clone THU-MAIC/OpenMAIC beside the dashboard first.",
    );
  }
  const corepack = corepackEntry();
  if (!corepack) {
    throw new Error(
      "corepack was not found next to this Node, and OpenMAIC installs with pnpm through it.",
    );
  }
  const destination = classroomRuntimeRoot();
  const staging = classroomStagingRoot(randomUUID().slice(0, 8));
  const previous = `${destination}.previous-${randomUUID().slice(0, 8)}`;
  const toolsDir = classroomToolsDir();

  state.step = "Copying the source";
  copySource(source, staging);
  applyImporterBuildFix(staging);
  writePnpmShims(toolsDir, corepack);

  // The running server holds files open on Windows; it restarts on the next run.
  stopService();
  if (fs.existsSync(destination)) fs.renameSync(destination, previous);
  try {
    fs.renameSync(staging, destination);
  } catch (error) {
    fs.rmSync(staging, { recursive: true, force: true });
    if (fs.existsSync(previous)) fs.renameSync(previous, destination);
    throw error;
  }

  try {
    const env = installEnvironment(toolsDir);
    await runStep(
      "Installing dependencies",
      process.execPath,
      [corepack, "pnpm", "install", "--frozen-lockfile"],
      { cwd: destination, env, timeoutMs: INSTALL_TIMEOUT_MS },
    );
    await runStep(
      "Building the app",
      process.execPath,
      [corepack, "pnpm", "run", "build"],
      { cwd: destination, env, timeoutMs: BUILD_TIMEOUT_MS },
    );
    if (!fs.existsSync(path.join(destination, ".next", "BUILD_ID"))) {
      throw new Error("The build finished without producing a servable app.");
    }
    ensureClassroomDataLink(path.join(destination, "data"));
  } catch (error) {
    state.step = "Restoring the previous runtime";
    fs.rmSync(destination, { recursive: true, force: true });
    if (fs.existsSync(previous)) fs.renameSync(previous, destination);
    throw error;
  }
  // A previous runtime from before the data junction existed may still hold
  // classrooms in a real `data/`; carry them over before it goes.
  const previousData = path.join(previous, "data");
  if (fs.lstatSync(previousData, { throwIfNoEntry: false })?.isDirectory()) {
    ensureClassroomDataLink(previousData);
  }
  fs.rmSync(previous, { recursive: true, force: true });
}

/**
 * Start setup in the background and return at once; `setupStatus()` reports
 * progress. A second press while one runs joins it rather than starting another.
 */
export function startClassroomSetup(): ClassroomSetupProgress {
  if (!state.running) {
    state.running = true;
    state.step = "Starting";
    state.log = "";
    state.error = "";
    state.startedAt = new Date().toISOString();
    state.finishedAt = null;
    state.promise = perform()
      .then(() => {
        state.step = "Ready";
      })
      .catch((error: unknown) => {
        state.error = error instanceof Error ? error.message : "Setup failed.";
        state.step = "Failed";
      })
      .finally(() => {
        state.running = false;
        state.child = null;
        state.finishedAt = new Date().toISOString();
        state.promise = null;
      });
  }
  return setupStatus().setup;
}

/** The in-flight setup, for a caller that wants to wait on it. */
export function classroomSetupPromise(): Promise<void> | null {
  return state.promise;
}
