// Shared semantic teaching requirements for introductions, lessons, and repairs.
// Length follows the teaching work, independently of subject and output format.
export const LEARN_LENGTH_PLANNING_RULES = `Plan lesson length from the teaching work:
- Every learning-unit record must also include expectedWordRange as [lowerEstimate, upperEstimate], using actual positive integers with upperEstimate >= lowerEstimate. Estimate each unit independently from its learning question, learner background, conceptual difficulty, required derivations, worked examples, and assigned source questions and artifacts. There is no standard word range or reading-time target to copy across units.
- These are advisory planning estimates, not minimums or caps. Lessons still require at least 1400 words of real explanatory prose, so plan lowerEstimate >= 1400. A complete explanation may be shorter or longer than its estimate while respecting that minimum. Split units only at coherent conceptual boundaries that improve learning, never merely to fit a word count.`;

export const LEARN_FOUNDATION_RULES = `Teach from the ground up (hard requirements for every learner-facing page):
- Assume a motivated beginner unless the learner explicitly supplies a different starting level. Hearing a word, seeing it in a title, or finding it in a source, tag, prerequisiteConcepts list, or course outline is not evidence of understanding it.
- Start with a familiar observation, concrete situation, or simple question. Explain the idea in everyday language before using its technical name to explain anything else. At first substantive use, say what the term means here and connect it to that concrete picture. Expanding an acronym or replacing a term with another unfamiliar term is not an explanation.
- Build each explanation from ideas already explained. Unpack any unfamiliar concept needed by a definition before relying on that definition; avoid circular definitions and chains of unexplained jargon. Each causal or logical step must say how or why it follows. Do not use "obviously", "simply", or "by definition" to hide a missing step.
- Use the Feynman method: explain in plain, precise language that the learner could retell in their own words, expose gaps, and fill those gaps before continuing. Simplicity must preserve the actual mechanism and its conditions, not replace it with a slogan, technical label, or vague analogy.
- Let length follow what the learner needs to understand the page's question at their starting level. Give difficult mechanisms, supported derivations, worked examples, and assigned questions enough space to explain every necessary step. For lesson pages, the prose minimum is 1400 words; overview and navigation pages stay proportionate to their role. Meet the applicable prose minimum through substantive teaching, then stop when the explanation is complete; remove repetition and tangents, and never compress to meet a word count or reading-time target. Any expectedWordRange, including one from an existing plan, is advisory and must yield to these teaching needs and the prose minimum.
- Give a small concrete example or worked reasoning step where it helps establish a new idea. Explain what corresponds to what in an analogy and where it stops applying. Distinguish an illustrative assumption from an established fact.
- Intuition and logic come before mathematics, every time. Before any equation appears, the reader must already hold the physical picture (what pushes what, what flows where, what grows when what grows) and the reason the relationship must have that shape — so that, told the equation is coming, they could guess its form. The equation then confirms the picture; it never introduces an idea. After displaying it, read it back in words: which quantity does what to which, and what happens at the limits (zero distance, very large charge, no time passing). A derivation is narrated as reasoning — what we know, what we want, why the next step is the natural one — never presented as a run of algebra to be accepted. A reader who skips every equation on the page should still come away understanding the mechanism.
- Explain the way Feynman explained: find the simplest honest picture of the mechanism, make it vivid and concrete, push it until it predicts something, then show where the simple picture stops being enough and what replaces it. Precision comes from choosing the right picture, not from stacking terminology.
- Motivate formulas before displaying them; explain the quantities, symbols, units where applicable, assumptions, and what the relationship lets the learner work out. Preserve required source formulas and question text verbatim, adding explanation around them.
- Establish a formula rather than only citing it whenever the contract says it can be established. Each required formula carries a grounding: "derived" means the source supports a real route to it, so show that route — state what it starts from, take the steps in order, and say what each step uses; "empirical" means it is measured or postulated, so say so plainly and give the evidence or reasoning that makes it credible; "axiom" means it is a definition or convention being adopted, so say what it fixes and why that choice; "asserted_in_source" means the source states it without support, so say that the result is taken as given here and name where the argument lives. Never pretend an empirical rule, axiom, or asserted result has been derived from first principles, and never leave a derivable result looking like something the learner must simply accept.
- Later pages may build on genuinely established ideas with a brief local reminder of the meaning needed now. A prior title or planned unit alone does not establish a concept. Do not repeat the whole course or global motivation; mustNotRepeat does not forbid a necessary prerequisite reminder.
- Verify every backward reference against the earlier lesson's actual explanation. A refusal or a mention does not establish a prerequisite. Explain the missing bridge locally before relying on it, or leave the dependent learning objective explicitly unresolved for repair.
- Complete the capability promised by the learning question. For a process with complementary stages (such as encoding, combining signals, and recovering a message), carry one consistent small example through all relevant stages, showing intermediate values and checking the result. Include an application question with worked feedback that requires the learner to use the mechanism, not just recall its name. Scale this to the question; do not invent unsupported calculations or make every optional derivation mandatory.
- Introductions, summaries, and navigation prose must obey the same first-use rule. A linked future topic may be named as a destination, but cannot do explanatory work before its meaning is taught. If a detail is premature, describe its observable role in plain words and defer the technical label or deeper mechanism.
- Stay within the supported source scope for everything the lesson asserts as physics, mathematics, method, number, or result. Build from the simplest supported starting point; if an essential prerequisite cannot be explained from the available evidence, state that specific prerequisite honestly rather than inventing a derivation or disguising it with terminology.
- Teach one line of reasoning. A page is one step in a chain that runs through the whole course: it begins from what the previous step established and ends somewhere the next step can begin. Order ideas by what they are made of, not by the subject's headings. A compound word is never the first thing explained: before "electromagnetism" the reader meets charge, then what a charge does at a distance, then what a moving charge does, and only then the name for their union. If a page cannot afford to explain a term, it cannot afford to use it.
- For every idea a page is responsible for, answer three questions in the prose, not as headings: how it works (the mechanism, step by step); why it is so or why it was needed (the observation that forced it, the problem it solved, or the argument that makes it necessary); and where it comes from (what it is derived from, or the experiment or reasoning that first established it). An idea that has been named and used but not given its how, why, and where-from has not been taught.
- Use origins when they carry meaning. When a word's origin explains what the thing does ("dielectric": across-which-electricity-passes; "current": something flowing) or the history of a discovery explains why a law has the form it has (which measurement was made, what it ruled out), say so in a sentence or two at the point where it helps. Only well-established facts you are certain of: no invented dates, attributions, or anecdotes, and nothing that would embarrass a historian; if unsure, leave it out. These sentences are orientation for the learner, never claims made on the sources' behalf.
- Depth before breadth. Take the page's one idea to the bottom — its mechanism, its limits, what it implies — before widening to related ideas. A paragraph that names four ideas and explains none is worse than a paragraph that explains one. Do not tour applications as a substitute for explaining the mechanism that makes them work.
- The assigned material is the floor, not the ceiling. Where the wider subject holds a standard deeper connection that a serious learner would want (the kind any graduate treatment mentions), state it in a short \`> [!info]\` callout marked as beyond this course's material: what the connection is, why it matters, and where it is usually studied. Keep it to established textbook-level knowledge, never a formula, number, or derivation the sources do not carry, never something that contradicts the sources, and never as a substitute for the assigned explanation. One such callout per page at most.
- Before returning, reread in learner order: could the reader explain each new term, follow why each step follows, say where each central idea comes from, and use the idea in a simple case using only what has been established? Repair any gap in the prose itself. Do not output this checklist.`;

export const LEARN_FOUNDATION_PLANNING_RULES = `Foundation planning requirements:
${LEARN_LENGTH_PLANNING_RULES}
- Identify the learner's actual starting knowledge; default to no subject-specific background. Separate familiarity with a name from an ability to explain it.
- Order units by conceptual dependencies. prerequisiteConcepts must identify meanings the learner needs, and newConcepts must identify meanings the unit will actually teach. Give each needed foundation an earlier teaching step or an explicit local explanation; never count an outline mention or later unit as prior teaching.
- Classify every sourceFormulas entry honestly with grounding and derivableFrom. Use "derived" only when the available evidence actually supports a route to the result, and list in derivableFrom the earlier anchor ids or prior unit results that route starts from. Use "empirical" for measured or postulated laws, "axiom" for definitions and adopted conventions, and "asserted_in_source" when the source states the result without supporting it. Classify by what the evidence supports, not by how fundamental the result feels; a famous law can still be empirical and a minor identity can still be derived.
- Use scope background for the minimum supported foundations needed to understand included material. If an essential foundation is unsupported, record that specific gap in caveats/warnings rather than silently assuming it or expanding the course without evidence.
- Evaluate bundled syllabus subtopics independently before declaring an entire item unsupported. Distinguish evidence absent from the selected sources from evidence absent only from the currently assigned anchors. Preserve supported subtopics and their evidence; name each remaining unsupported subtopic separately. Never infer support for one topology, material, or access method from evidence for a neighboring one.
- Keep summaries and section purposes understandable before the units they introduce: describe the concrete question or capability, explain any technical label doing explanatory work, and leave detailed mechanisms to their owning units.
- A worked example, a numerical case, or a named system instance (a GSM frame count, a D-AMPS slot plan, a trunk-sizing calculation) is not a unit by itself: it belongs inside the unit whose concept it exercises, as that unit's concrete instance. Create a separate unit only for a new concept, mechanism, or result the learner must be able to reproduce; a run of units that each apply the same idea to a different example is the same unit over-split (live 2026-09-16: five capacity calculations became five units).
- Plan one line of reasoning, not a table of contents. Units are steps in a single chain: each unit's title names the one move it makes, and each unit's newConcepts are the meanings the next unit may rely on. A title that lists topics ("Work, Potential, Energy, and Current"; "Gradient, Divergence, Curl, and Integral Theorems") is a heading, not a teaching step: split it into the units it hides, in dependency order, each with its own learning question.
- The first unit of a course starts from the most elementary observable thing in the subject — the phenomenon a learner can point at — not from the subject's name or its applications. The name is earned once its parts have been taught. Applications and the "why this matters" tour come after the mechanism they depend on, never in place of it.
- Plan depth per unit: a unit's learningQuestion must be answerable to the bottom (mechanism, why it must be so, where it comes from) within that unit. When an assigned reading or source section carries more than one such question, plan more than one unit; do not let one unit skim several ideas.
- When the syllabus assigns numbered sections of a work to a unit, treat one assigned section as roughly one conceptual move: an assigned section that teaches a distinct idea normally earns its own learning unit, in the order the assigned work presents it.`;

export const LEARN_FOUNDATION_REVIEW_RULES = `Foundation review:
- Apply the ground-up teaching requirements to complete bodyText, orientationPages, and section indexBodyText in learner order, respecting the declared entry level and background in scopeContract. Check actual explanations, not just newConcepts, prerequisiteConcepts, tags, titles, or the presence of an example.
- Report an explanation_gap when understanding depends on an unintroduced technical term, circular/jargon-only definition, unexplained prerequisite, missing causal/derivation step, or misleading simplification. A substantial gap that prevents understanding is blocking; an optional extra example or stylistic preference is not.
- Check prerequisite closure against actual earlier prose: "as we established" is a claim to verify, including when that earlier page refused to teach the concept. Distinguish encountered, explained, and unresolved prerequisites. Check that the central learning question can be answered and applied from the garden alone; a label, optional-limit note, or classification survey cannot stand in for the promised mechanism. Identify the exact missing step or failed application rather than demanding all textbook mathematics.
- Beyond the applicable prose minimum, judge depth by whether the learner can follow and apply the explanation. Do not fail a complete page for falling outside expectedWordRange or request padding or compression just to reach it; identify the specific missing explanation or unnecessary repetition instead.
- Quote the exact passage, identify the missing meaning or reasoning step and why it is needed at that point, and request a focused plain-language bridge before the dependent claim. Use unit_page with pagePath for lessons/orientation pages and section_index with sectionPath for section introductions.
- Do not flag ordinary vocabulary, an explicitly stated entry prerequisite, a concept actually explained earlier with an adequate local reminder, or a future-topic link that does no explanatory work. Do not demand the entire subject's foundations on every page. Missing text in a truncated excerpt is not evidence of a teaching gap.
- Orientation pages (Topic Overview, Learning Map) are read before any lesson, so nothing has been explained earlier. A technical term, abbreviation, or unit that such a page uses inside a sentence that explains, compares, or gives a reason ("pooling channels improves the trunk's statistical efficiency", "users are separated through code structure") is doing explanatory work: report an explanation_gap targeting unit_page with that pagePath unless the page itself explains the term in plain words. A one-word gloss or restated name is not an explanation.
- Report an explanation_gap when a page's central idea is named and used but never given its mechanism, its reason (why it is so or why it was needed), or its origin (what it derives from or how it was established) — a page that surveys several ideas at the level of a definition each is superficial, and the issue must name the idea that was left shallow and which of the three is missing.
- Report an explanation_gap when a compound or technical name is explained before the parts it is made of ("electromagnetism" before charge, electric effect, and magnetic effect), or when a page opens on applications of a mechanism the learner has not yet been shown.
- Report an explanation_gap when an equation appears before the reader has been given, in words, the picture and the reason it formalizes — a formula that introduces an idea rather than confirming one — or when a derivation is presented as algebra without the reasoning that makes each step natural. Quote the equation and name the sentence of intuition that should precede it.
- Report contrastive-negation teaching ("X is not about A; it is about B", "far from being A", "rather than A, B"), filler ("merely", "crucial", "at its core", "serves as", "delve"), and sentences no person would say aloud to a student ("readily apparent upon measurement") as warning-severity "other" issues, quoting the sentence and asking for a direct statement of what the thing is or does. Deterministic counting already rejects pages with more than two; report the ones that remain.
- Length is judged the way a textbook editor judges it: every paragraph must add mechanism, a condition, a consequence, an example, or a step the argument needs. Report restatement as a warning-severity "other" issue — a paragraph that says again what an earlier one established, a closing summary that repeats the page instead of connecting its ideas, a transition that only announces what comes next — quoting the passage and asking for its removal, not its rewording. A long page whose every paragraph earns its place is correct; a short page is not made better by adding one that does not.
- A brief etymology or discovery-history sentence, and a single \`> [!info]\` callout marked as beyond the course material, are permitted orientation, not source gaps. Flag one only when it states a formula, number, or derivation the sources do not carry, contradicts the sources, is doing the explanatory work the assigned material should do, or asserts a historical fact that is wrong or invented.`;
