// The Postiz Docker Compose stack.
//
// Breadboard runs Postiz's *upstream* compose file untouched and layers a
// generated override on top. Nothing in the vendored clone is edited, so
// pulling upstream stays a plain `git pull`, while the override carries the
// things that must not ship as upstream defaults: a real JWT secret, the port
// Breadboard published, and whatever social OAuth apps the user configured.
//
// The override also sets NOT_SECURED, which makes Postiz return its auth JWT in
// a response header instead of a Secure cookie. That is what lets ./bootstrap.ts
// register the first account over plain http on localhost.

import { randomBytes } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import path from "node:path";

import type { SocialsManagerConfig, PostizCredentials } from "./config.ts";
import { composeCommand, ensureDockerRunning, run, type DockerStatus } from "./docker.ts";

export type StackState =
  | "running"
  | "starting"
  | "stopped"
  | "docker_unavailable"
  | "not_installed";

export interface StackStatus {
  state: StackState;
  docker: DockerStatus;
  /** True once the Postiz HTTP endpoint answers. */
  reachable: boolean;
  reason?: string;
}

/** Social OAuth apps Postiz reads from its environment, passed through when set. */
const SOCIAL_ENV_KEYS = [
  "X_API_KEY", "X_API_SECRET", "X_URL",
  "LINKEDIN_CLIENT_ID", "LINKEDIN_CLIENT_SECRET",
  "REDDIT_CLIENT_ID", "REDDIT_CLIENT_SECRET",
  "GITHUB_CLIENT_ID", "GITHUB_CLIENT_SECRET",
  "THREADS_APP_ID", "THREADS_APP_SECRET",
  "FACEBOOK_APP_ID", "FACEBOOK_APP_SECRET",
  "INSTAGRAM_APP_ID", "INSTAGRAM_APP_SECRET",
  "YOUTUBE_CLIENT_ID", "YOUTUBE_CLIENT_SECRET",
  "GOOGLE_GMB_CLIENT_ID", "GOOGLE_GMB_CLIENT_SECRET",
  "TIKTOK_CLIENT_ID", "TIKTOK_CLIENT_SECRET",
  "PINTEREST_CLIENT_ID", "PINTEREST_CLIENT_SECRET",
  "DRIBBBLE_CLIENT_ID", "DRIBBBLE_CLIENT_SECRET",
  "TUMBLR_CLIENT_ID", "TUMBLR_CLIENT_SECRET",
  "DISCORD_CLIENT_ID", "DISCORD_CLIENT_SECRET", "DISCORD_BOT_TOKEN_ID",
  "SLACK_ID", "SLACK_SECRET", "SLACK_SIGNING_SECRET",
  "KICK_CLIENT_ID", "KICK_SECRET",
  "TWITCH_CLIENT_ID", "TWITCH_CLIENT_SECRET",
  "WHOP_CLIENT_ID",
  "VK_ID",
  "MEWE_APP_ID", "MEWE_API_KEY", "MEWE_HOST",
  "NEYNAR_CLIENT_ID", "NEYNAR_SECRET_KEY",
  "TELEGRAM_BOT_NAME", "TELEGRAM_TOKEN",
] as const;

function quote(value: string): string {
  return `'${value.replaceAll("'", "''")}'`;
}

export function readCredentials(config: SocialsManagerConfig): PostizCredentials | null {
  try {
    const parsed = JSON.parse(
      readFileSync(config.credentialsFile, "utf8"),
    ) as Partial<PostizCredentials>;
    if (!parsed.email || !parsed.password || !parsed.jwtSecret) return null;
    return {
      email: parsed.email,
      password: parsed.password,
      apiKey: parsed.apiKey ?? "",
      jwtSecret: parsed.jwtSecret,
      createdAt: parsed.createdAt ?? new Date().toISOString(),
    };
  } catch {
    return null;
  }
}

export function writeCredentials(
  config: SocialsManagerConfig,
  credentials: PostizCredentials,
): void {
  mkdirSync(config.stateDir, { recursive: true });
  writeFileSync(
    config.credentialsFile,
    `${JSON.stringify(credentials, null, 2)}\n`,
    { encoding: "utf8", mode: 0o600 },
  );
}

/**
 * Mint the local Postiz account on first use. The password is never shown to
 * anyone: Breadboard is the only client, and it reads it back from this file.
 */
export function ensureCredentials(config: SocialsManagerConfig): PostizCredentials {
  const existing = readCredentials(config);
  if (existing) return existing;
  const credentials: PostizCredentials = {
    email: "breadboard@localhost.local",
    password: randomBytes(24).toString("base64url"),
    apiKey: "",
    jwtSecret: randomBytes(48).toString("base64url"),
    createdAt: new Date().toISOString(),
  };
  writeCredentials(config, credentials);
  return credentials;
}

export function upstreamComposeFile(config: SocialsManagerConfig): string {
  return path.join(config.cloneRoot, "docker-compose.yaml");
}

/** Generate the override layered over Postiz's own compose file. */
export function renderOverride(
  config: SocialsManagerConfig,
  credentials: PostizCredentials,
  env: NodeJS.ProcessEnv = process.env,
): string {
  const port = new URL(config.baseUrl).port || "80";
  const social = SOCIAL_ENV_KEYS.flatMap((key) => {
    const value = env[key]?.trim();
    return value ? [`      ${key}: ${quote(value)}`] : [];
  });

  return [
    "# Generated by Breadboard. Layered over postiz-app/docker-compose.yaml;",
    "# edit Breadboard's settings rather than this file — it is rewritten on start.",
    "services:",
    "  postiz:",
    "    environment:",
    `      MAIN_URL: ${quote(config.baseUrl)}`,
    `      FRONTEND_URL: ${quote(config.baseUrl)}`,
    `      NEXT_PUBLIC_BACKEND_URL: ${quote(`${config.baseUrl}/api`)}`,
    `      JWT_SECRET: ${quote(credentials.jwtSecret)}`,
    // Plain http on loopback: Secure/SameSite=None cookies would be dropped, and
    // the auth JWT has to come back in a header for headless bootstrap.
    "      NOT_SECURED: 'true'",
    "      DISABLE_REGISTRATION: 'false'",
    ...social,
    // Compose normally appends ports with different host IPs. `!override`
    // replaces the upstream 0.0.0.0 binding instead of publishing both.
    "    ports: !override",
    `      - '127.0.0.1:${port}:5000'`,
    "    depends_on:",
    "      temporal:",
    "        condition: service_healthy",
    "  temporal:",
    "    healthcheck:",
    "      test: ['CMD', 'temporal', 'operator', 'cluster', 'health', '--address', 'temporal:7233']",
    "      interval: 5s",
    "      timeout: 5s",
    "      retries: 30",
    "      start_period: 20s",
    "",
  ].join("\n");
}

export function writeOverride(
  config: SocialsManagerConfig,
  credentials: PostizCredentials,
  env: NodeJS.ProcessEnv = process.env,
): string {
  mkdirSync(config.stateDir, { recursive: true });
  writeFileSync(config.overrideFile, renderOverride(config, credentials, env), "utf8");
  return config.overrideFile;
}

/** Does the Postiz backend answer yet (not merely its frontend/nginx shell)? */
export async function reachable(config: SocialsManagerConfig): Promise<boolean> {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), 3_000);
  try {
    const response = await fetch(`${config.appApiUrl}/auth/can-register`, {
      cache: "no-store",
      redirect: "manual",
      signal: controller.signal,
    });
    return response.ok;
  } catch {
    return false;
  } finally {
    clearTimeout(timer);
  }
}

export async function stackStatus(config: SocialsManagerConfig): Promise<StackStatus> {
  if (await reachable(config)) {
    return {
      state: "running",
      reachable: true,
      docker: {
        cliInstalled: true,
        desktopInstalled: true,
        daemonRunning: true,
      },
    };
  }
  const docker = await ensureDockerRunning({
    timeoutMs: 0,
    autoStart: false,
  });
  if (!docker.cliInstalled || !docker.desktopInstalled) {
    return {
      state: "not_installed",
      reachable: false,
      docker,
      reason: docker.reason ?? "Docker is not installed.",
    };
  }
  return {
    state: docker.daemonRunning ? "stopped" : "docker_unavailable",
    reachable: false,
    docker,
    reason: docker.reason,
  };
}

const globalStack = globalThis as typeof globalThis & {
  __breadboardSocialsManagerStart?: Promise<StackStatus> | null;
};

/**
 * Bring the stack up in the background: quietly start an available container
 * engine if the daemon is down, write the override, then `compose up -d`. Concurrent callers share one
 * attempt. Returns as soon as the compose command finishes, which is *before*
 * Postiz finishes migrating — callers poll `reachable` for readiness.
 */
export type PostizStackOutput = (stream: "stdout" | "stderr", chunk: string) => void;

export function startStack(
  config: SocialsManagerConfig,
  onOutput?: PostizStackOutput,
): Promise<StackStatus> {
  if (globalStack.__breadboardSocialsManagerStart) {
    return globalStack.__breadboardSocialsManagerStart;
  }
  const attempt = (async (): Promise<StackStatus> => {
    // The engine's cold start dominates: give it a real budget.
    const docker = await ensureDockerRunning({
      timeoutMs: 90_000,
      autoStart: config.autoStartDocker,
      suppressUi: config.suppressDockerUi,
    });
    if (!docker.daemonRunning) {
      return {
        state: docker.cliInstalled && docker.desktopInstalled
          ? "docker_unavailable"
          : "not_installed",
        reachable: false,
        docker,
        reason: docker.reason,
      };
    }

    const compose = await composeCommand();
    if (!compose) {
      return {
        state: "not_installed",
        reachable: false,
        docker,
        reason: "Docker Compose is not available.",
      };
    }

    const credentials = ensureCredentials(config);
    const override = writeOverride(config, credentials);
    const [command, ...prefix] = compose;
    const composeArgs = [
      ...prefix,
      "--project-name",
      config.projectName,
      "--file",
      upstreamComposeFile(config),
      "--file",
      override,
      "up",
      "--detach",
    ];
    let result = await run(command, composeArgs, {
      cwd: config.cloneRoot,
      timeoutMs: 600_000,
      onStdout: onOutput ? (chunk) => onOutput("stdout", chunk) : undefined,
      onStderr: onOutput ? (chunk) => onOutput("stderr", chunk) : undefined,
    });
    // Docker Desktop can hold the old port proxy for a moment while Compose
    // recreates a container whose binding changed. Retrying the idempotent `up`
    // also recovers other short engine races without hiding the final error.
    for (
      let retry = 0;
      result.code !== 0 &&
      retry < 2 &&
      /address already in use|external connectivity|daemon is not running|connection refused/i.test(
        result.stderr,
      );
      retry += 1
    ) {
      await new Promise((resolve) => setTimeout(resolve, 2_000));
      result = await run(command, composeArgs, {
        cwd: config.cloneRoot,
        timeoutMs: 600_000,
        onStdout: onOutput ? (chunk) => onOutput("stdout", chunk) : undefined,
        onStderr: onOutput ? (chunk) => onOutput("stderr", chunk) : undefined,
      });
    }

    if (result.code !== 0) {
      return {
        state: "stopped",
        reachable: false,
        docker,
        reason:
          result.stderr.trim().split(/\r?\n/).slice(-1)[0] ||
          "Postiz containers failed to start.",
      };
    }
    const isReachable = await reachable(config);
    return {
      state: isReachable ? "running" : "starting",
      reachable: isReachable,
      docker,
    };
  })().finally(() => {
    globalStack.__breadboardSocialsManagerStart = null;
  });
  globalStack.__breadboardSocialsManagerStart = attempt;
  return attempt;
}

export async function stopStack(config: SocialsManagerConfig): Promise<boolean> {
  const compose = await composeCommand();
  if (!compose) return false;
  const [command, ...prefix] = compose;
  const result = await run(
    command,
    [
      ...prefix,
      "--project-name",
      config.projectName,
      "--file",
      upstreamComposeFile(config),
      "--file",
      config.overrideFile,
      "down",
    ],
    { cwd: config.cloneRoot, timeoutMs: 180_000 },
  );
  return result.code === 0;
}

/** Poll until Postiz answers, or the budget runs out. */
export async function waitForReady(
  config: SocialsManagerConfig,
  timeoutMs: number,
): Promise<boolean> {
  const deadline = Date.now() + timeoutMs;
  while (Date.now() < deadline) {
    if (await reachable(config)) return true;
    await new Promise((resolve) => setTimeout(resolve, 1_500));
  }
  return false;
}
